### PR TITLE
Airtable (Independent Publisher)

### PR DESCRIPTION
**Pull request by last72**
Due to Airtable requeirng PKCE. Custom connector does not support PKCE natively

Airtable (endpoint) changed Auth requirements and existing method does not work.

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [X] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [X] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [X] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [X] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [X] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by troystaylor** [comment]
@last72 Are you hoping to release a V2 of this connector? Do you need assistance with custom code for the new OAuth method?

**Comment by last72** [comment]
@troystaylor I had a look some time ago but it was not possible to implement PKCE without heavy workarounds.

I'm happy to try new

PKCE: https://oauth.net/2/pkce/
API Docs: https://airtable.com/developers/web/api/oauth-reference#authorization-request-query

**Comment by troystaylor** [comment]
@last72 I'm halfway there. Users will still need to complete the OAuth manually, but it will be usable.
image

**Review by vmanoharas — COMMENTED** [review]
Hello @last72 
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Review by vmanoharas — APPROVED** [review]
Hello @last72
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by troystaylor** [comment]
@last72 I've got it working - auth, token and refresh. I'll send you an email. With a working authentication, are you interested in releasing a new version of the connector, with or without other actions now available in the API, or do you need assistance re-releasing the connector?
image

**Comment by troystaylor** [comment]
@last72 I was reviewing your apiDefinition file and noticed that your authentication method is already set to personal access token as a Bearer token. In reviewing in the documentation from Airtable, personal access tokens will continue to work, but API keys will not. Users of your connector are probably seeing errors because they are trying to continue using API keys. I would confirm, but this means that you will not need to deprecate your connector.

https://support.airtable.com/docs/airtable-api-key-deprecation-notice

**Comment by vmanoharas** [comment]
Thanks @troystaylor, @last72 kindly let me know should we proceed this connector for deployment or stop? Please confirm, as it is not picked up for deployment cycle.

**Comment by last72** [comment]
@troystaylor @vmanoharas I was away last week. Apologies for late responses.

Thanks for the work Troy. I'll continue working on it and re-release. If you can send me the swagger with your additional 3 actions, it would help me develop the connector faster.

I'll need to review and test on myside as well. And re-release because it had some usage among community

**Comment by vmanoharas** [comment]
Hello @last72, we have processed this connector for deployment today. and it will be picked to deployment on this Friday. Please re-submit this connector with new changes, if needed. Thanks!

**Comment by last72** [comment]
@troystaylor are you able to send me the swagger file with Airtable OAuth please? feel free to continue work on this and publish v2 of Airtable connector yourself if it is easier

**Comment by troystaylor** [comment]
I don't think any of my work is necessary. Your connector will authenticate if you use 'Bearer Personal_Access_Token' as an Authorization header: 
image

**Comment by vmanoharas** [comment]
Hello @last72, 

I am following up on this, kindly provide an update.

**Comment by vmanoharas** [comment]
Hello Partner,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Pull request merged**
