### PR TITLE
Atbot custom connector updates

### PR DESCRIPTION
**Pull request by MickH3**
Added 2 additional actions.

---
Please check the following conditions for your PR.

- [ X] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ X] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Comment by dougelliott** [comment]
@MickH3 Could the conflicts be resolved please? Thanks in advance!

**Comment by MickH3** [comment]
Hi @dougelliott I am not seeing an option to take action to resolve the conflicts.  I want to keep all of the new updates but I don't have a button or other way to select the version to keep.

Thanks!

Mick

**Comment by dougelliott** [comment]
> Hi @dougelliott I am not seeing an option to take action to resolve the conflicts. I want to keep all of the new updates but I don't have a button or other way to select the version to keep.
> 
> Thanks!
> 
> Mick

@MickH3 You should be able to [sync your fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) and address the conflicts locally, then push your changes with the version you intend :)

**Comment by dougelliott** [comment]
Closing due to inactivity. @MickH3 - Please feel free to open another PR when you have the time :)

**Pull request closed without merging**
