### PR TITLE
Update - SMS Wireless Services (Independent Publisher)

### PR DESCRIPTION
**Pull request by SietseBakkerViaData**
Remove connectionParameter KEY

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [X] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by Amjed-Ayoub** [comment]
[[certify-connector]]

**Comment by Amjed-Ayoub** [comment]
Hello @SietseBakkerViaData ,
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks. 
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by Amjed-Ayoub** [comment]
Hello @SietseBakkerViaData,
I hope you are doing well.
Your connector is in production deployment and queued up for the next deployment schedule. This process typically takes 3-4 weeks. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps.
Please let us know if you have any questions.
Thank you very much for working with us.

**Review by Amjed-Ayoub — APPROVED** [review]
Hello @SietseBakkerViaData,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Comment by SietseBakkerViaData** [comment]
Hello Amjed Ayoub,

We are almost 7 weeks after the email below. Unfortunately, the adjustment we have made is not yet reflected in production. Has the rollout not happened yet? Or is something else wrong?

We have removed the "api_key" from the "connectionParameters" in the new version. But the Key is still there (https://learn.microsoft.com/en-us/connectors/smswirelessserviceip/)
***@***.***


Sietse Bakker
Teamleider technisch software consultants
Businesspark Friesland West 45, 8447 SL Heerenveen
viadata.nl | linkedin.com | 06 - 30 333 249 | 0513 - 619 350
Niet aanwezig op donderdag
Van: Amjed Ayoub ***@***.***>
Verzonden: zaterdag 11 februari 2023 01:09
Aan: microsoft/PowerPlatformConnectors ***@***.***>
CC: Bakker, Sietse ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [microsoft/PowerPlatformConnectors] Update - SMS Wireless Services (Independent Publisher) (PR #2369)


Hello @SietseBakkerViaData<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSietseBakkerViaData&data=05%7C01%7Cs.bakker%40viadata.nl%7C21f652176b044348e59c08db0bc431e6%7C932ad8e522e441379aed2677785182cf%7C0%7C0%7C638116709523831093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0iKxYeLBnzd4UrWT3%2Bpl%2B8xzgJYfG%2FdpycZWW96cb2g%3D&reserved=0>,
I hope you are doing well.
Your connector is in production deployment and queued up for the next deployment schedule. This process typically takes 3-4 weeks. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps.
Please let us know if you have any questions.
Thank you very much for working with us.

-

**Comment by Amjed-Ayoub** [comment]
Hello @SietseBakkerViaData thank you so much for reaching out and bringing our attention to this. 
We found the issue in one of the connector files which we have internally. we will fix and redeploy the connector. 
Please expect this to be resolved within 3-4 weeks.

Please accept our apologies for this mistake and for any inconvenience it may have caused.

Thank you so much again for your patience and understanding.

**Pull request merged**
