### PR TITLE
Square Payments (Independent Publisher) v1.2

### PR DESCRIPTION
**Pull request by troystaylor**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [X] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [X] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by v-EgorKozhadei** [comment]
[[certify-connector]]

**Comment by v-EgorKozhadei** [comment]
Hello @troystaylor, 

I hope you are doing well. 

Congratulations, your connector is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.  

Please let us know if you have any questions. 

Thank you very much for working with us.

**Comment by sriyen-msft** [comment]
[[certify-connector]]

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor,
I hope you are doing well.
Your connector is in production deployment and queued up for the next deployment schedule. This process typically takes 3-4 weeks. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps.
Please let us know if you have any questions.
Thank you very much for working with us.

**Review by sriyen-msft — APPROVED** [review]

**Comment by sriyen-msft** [comment]
@troystaylor Apologies for the delay in response. 

Congratulations! The deployment of your connector and documentation page is now complete, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program, Thanks.

**Comment by vmanoharas** [comment]
Hi @troystaylor, 

Our localization team identified errors during the localization process. Some strings exceed the allowed limit and need to be shortened. Please ensure these strings are within 500 characters. Kindly review and update them accordingly and resubmit the PR for certification. 

We sincerely appreciate your help in this regard.  

Line[1076]: "description": "If true, the response will include additional objects that are related to the requested objects, as follows: If the objects field of the response contains a CatalogItem, its associated CatalogCategory objects, CatalogTax objects, CatalogImage objects and CatalogModifierLists will be returned in the related_objects field of the response. If the objects field of the response contains a CatalogItemVariation, its parent CatalogItem will be returned in the related_objects field of the response.",
 
line[1316]:"description": "Creates or updates up to 10,000 target objects based on the provided list of objects. The target objects are grouped into batches and each batch is inserted/updated in an all-or-nothing manner. If an object within a batch is malformed in some way, or violates a database constraint, the entire batch containing that item will be disregarded. However, other batches in the same request may still succeed. Each batch may contain up to 1,000 objects, and batches will be processed in order as long as the total object count for the request (items, variations, modifier lists, discounts, and taxes) is no more than 10,000.",
 
line[2190]:"description": "If true, the response will include additional objects that are related to the requested object, as follows: If the object field of the response contains a CatalogItem, its associated CatalogCategory, CatalogTax, CatalogImage and CatalogModifierList objects will be returned in the related_objects field of the response. If the object field of the response contains a CatalogItemVariation, its parent CatalogItem will be returned in the related_objects field of the response.",
 
line[12331]:"description": "Cancels (voids) a payment identified by the idempotency key that is specified in the request. Use this method when the status of a CreatePayment request is unknown (for example, after you send a CreatePayment request, a network error occurs and you do not get a response). In this case, you can direct Square to cancel the payment using this endpoint. In the request, you provide the same idempotency key that you provided in your CreatePayment request that you want to cancel. After canceling the payment, you can submit your CreatePayment request again. Note that if no payment with the specified idempotency key is found, no action is taken and the endpoint returns successfully.",
line[16307]:"scopes": {
        "BANK_ACCOUNTS_READ CASH_DRAWER_READ CUSTOMERS_READ CUSTOMERS_WRITE DEVICE_CREDENTIAL_MANAGEMENT EMPLOYEES_READ EMPLOYEES_WRITE INVENTORY_READ INVENTORY_WRITE ITEMS_READ ITEMS_WRITE LOYALTY_READ LOYALTY_WRITE MERCHANT_PROFILE_READ ORDERS_READ ORDERS_WRITE PAYMENTS_READ PAYMENTS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS PAYMENTS_WRITE_IN_PERSON SETTLEMENTS_READ TIMECARDS_READ TIMECARDS_WRITE TIMECARDS_SETTINGS_READ TIMECARDS_SETTINGS_WRITE APPOINTMENTS_READ APPOINTMENTS_WRITE APPOINTMENTS_BUSINESS_SETTINGS_READ INVOICES_READ INVOICES_WRITE SUBSCRIPTIONS_READ SUBSCRIPTIONS_WRITE DISPUTES_READ DISPUTES_WRITE GIFTCARDS_READ GIFTCARDS_WRITE ONLINE_STORE_SNIPPETS_WRITE ONLINE_STORE_SNIPPETS_READ ONLINE_STORE_SITE_READ PAYMENTS_WRITE_SHARED_ONFILE": "BANK_ACCOUNTS_READ CASH_DRAWER_READ CUSTOMERS_READ CUSTOMERS_WRITE DEVICE_CREDENTIAL_MANAGEMENT EMPLOYEES_READ EMPLOYEES_WRITE INVENTORY_READ INVENTORY_WRITE ITEMS_READ ITEMS_WRITE LOYALTY_READ LOYALTY_WRITE MERCHANT_PROFILE_READ ORDERS_READ ORDERS_WRITE PAYMENTS_READ PAYMENTS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS PAYMENTS_WRITE_IN_PERSON SETTLEMENTS_READ TIMECARDS_READ TIMECARDS_WRITE TIMECARDS_SETTINGS_READ TIMECARDS_SETTINGS_WRITE APPOINTMENTS_READ APPOINTMENTS_WRITE APPOINTMENTS_BUSINESS_SETTINGS_READ INVOICES_READ INVOICES_WRITE SUBSCRIPTIONS_READ SUBSCRIPTIONS_WRITE DISPUTES_READ DISPUTES_WRITE GIFTCARDS_READ GIFTCARDS_WRITE ONLINE_STORE_SNIPPETS_WRITE ONLINE_STORE_SNIPPETS_READ ONLINE_STORE_SITE_READ PAYMENTS_WRITE_SHARED_ONFILE"
      }
line[16314]:  "security": [
    {
      "oauth2_auth": [
        "BANK_ACCOUNTS_READ CASH_DRAWER_READ CUSTOMERS_READ CUSTOMERS_WRITE DEVICE_CREDENTIAL_MANAGEMENT EMPLOYEES_READ EMPLOYEES_WRITE INVENTORY_READ INVENTORY_WRITE ITEMS_READ ITEMS_WRITE LOYALTY_READ LOYALTY_WRITE MERCHANT_PROFILE_READ ORDERS_READ ORDERS_WRITE PAYMENTS_READ PAYMENTS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS PAYMENTS_WRITE_IN_PERSON SETTLEMENTS_READ TIMECARDS_READ TIMECARDS_WRITE TIMECARDS_SETTINGS_READ TIMECARDS_SETTINGS_WRITE APPOINTMENTS_READ APPOINTMENTS_WRITE APPOINTMENTS_BUSINESS_SETTINGS_READ INVOICES_READ INVOICES_WRITE SUBSCRIPTIONS_READ SUBSCRIPTIONS_WRITE DISPUTES_READ DISPUTES_WRITE GIFTCARDS_READ GIFTCARDS_WRITE ONLINE_STORE_SNIPPETS_WRITE ONLINE_STORE_SNIPPETS_READ ONLINE_STORE_SITE_READ PAYMENTS_WRITE_SHARED_ONFILE"
      ]
    }

**Pull request merged**
