### PR TITLE
HubSpot CRM (Independent Publisher) Remove reports scope

### PR DESCRIPTION
**Pull request by troystaylor**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by Amjed-Ayoub** [comment]
[[certify-connector]]

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor,
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks. 
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by salaros** [comment]
@Amjed-Ayoub 3-4 weeks? Is this a joke? Yesterday I tried to create a Power Automate flow with HubSpot and discovered that I won't be able to do it for at least 3 weeks/1 month. It doesn't make any sense

**Comment by troystaylor** [comment]
A couple of weeks is not a joke. This is a Microsoft-sponsored open-source project that still follows the same certification process as any other connector submitted by an API service. I am a community member in the Microsoft Power Platform that has contributed this connector as an open-source contribution. You are welcome to make the API calls yourself using the HTTP connector.

**Comment by salaros** [comment]
@troystaylor I was just looking for an immediate solution (( because I needed it yesterday. It's just a little bit frustrating

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor,
I hope you are doing well.
Your connector is in production deployment and queued up for the next deployment schedule. This process typically takes 3-4 weeks. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps.
Please let us know if you have any questions.
Thank you very much for working with us.

**Review by Amjed-Ayoub — APPROVED** [review]
Hello @troystaylor ,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Comment by DamienOCNLondon** [comment]
Hello @troystaylor 
I have been eagerly following this thread in the hope that we can create some flows from Office 365 into HubSpot. Please can you confirm if this will work with the free version of Hubspot?
Thank you :)

**Comment by salaros** [comment]
Hi @DamienOCNLondon it's not working neither on free nor on paid version (my case, I have Starter Subscription) if you are trying to link HubSpot to PowerAutomate for the first time (like I am). 

It's been weeks and the issue still persist, I don't know what's going on and why is it taking months to get deployed.
Seems like this extension will never work again for new users and after existing OAuth2 connections are expired nobody will be ever able to re-link PowerAutomate to HubSpot again too 😢 

image

image

**Comment by DamienOCNLondon** [comment]
Thanks for that info @salaros at least I know it's not a licencing thing.

Someone has gone to a lot of effort to try and connect Hubspot to Power Automate so lets hope they won't want to see their efforts wasted.

**Pull request merged**
