### PR TITLE
General renaming of "PROS AI for Sales Copilot" to "PROS AI"

### PR DESCRIPTION
**Pull request by pros-iwaldman**
General renaming of "PROS AI for Sales Copilot" to "PROS AI". 

---
- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

### CODE REVIEW

**Review by vmanoharas — COMMENTED** [review]
Hello @pros-iwaldman, 

Your merge commit has an issue, it has not merged properly, it is conflicting with other connector repos, please refer Swagger validation checker errors. Please recommit or close this PR and open a new PR. Please don't merge it until the review is completed.

**Comment by pros-iwaldman** [comment]
Hi @vmanoharas 

I cannot view the logs and all I get is "The path template has been changed for the operation. ValuePath: operation/DownloadFile Source: NewSwagger". 

Please note that we are trying to rename the connector in this PR. Should I delete the existing connector and submit as a "new" connector?

Any thoughts? 

Regards,
Irvin

**Comment by pros-iwaldman** [comment]
I executed the `paconn validate` command, and it didn't return any errors. The warnings it displayed have been present previously.

image

**Comment by pros-iwaldman** [comment]
Closing per recommendation.

**Comment by pros-iwaldman** [comment]
Closing per recommendation.

**Pull request closed without merging**
