### PR TITLE
Updated connector artifacts

### PR DESCRIPTION
**Pull request by mittork**
no functional changes, only metadata added and brandColor updated.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### CODE REVIEW

**Comment by dougelliott** [comment]
@mittork Checking in on the `readme.md` requirement that Srikanth mentioned above. Please let us know if there are any questions.

**Comment by mittork** [comment]
Hi @dougelliott no questions, we will put the readme.md soon; but it will take some time. Feel free to abandon the PR for now if you don't want to keep it open.

**Comment by dougelliott** [comment]
Hey @mittork - No worries, we can keep the PR open while you work on the readme. Go ahead and tag us once you're ready and we'll give things a review.

**Comment by mmurshed** [comment]
> Hey @mittork - No worries, we can keep the PR open while you work on the readme. Go ahead and tag us once you're ready and we'll give things a review.

@mittork any update on this? @dougelliott @sriyen-msft

**Comment by mittork** [comment]
> > Hey @mittork - No worries, we can keep the PR open while you work on the readme. Go ahead and tag us once you're ready and we'll give things a review.
> 
> @mittork any update on this? @dougelliott @sriyen-msft

@mmurshed not yet.

**Comment by sriyen-msft** [comment]
Followed up with the partner to address the comments mentioned in the PR

**Comment by mamurshe** [comment]
@sriyen-msft @mittork Any update on this?

**Comment by mittork** [comment]
> @sriyen-msft @mittork Any update on this?

@mamurshe not yet, feel free to reject the PR for now; I will open new one once all is set.

**Pull request closed without merging**
