### PR TITLE
Power tools pro v4 1

### PR DESCRIPTION
**Pull request by eshupps**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

Screenshots attached.

powertools-pro-2023201-1
powertools-pro-2023201-2
powertools-pro-2023201-3
powertools-pro-2023201-4
powertools-pro-test-2023201

### CODE REVIEW

**Comment by Amjed-Ayoub** [comment]
@eshupps thank you so much for submitting your new connectors updates. May I ask you please to create a separate PR for each connector? this will make the ISV Studio submission easier using the commit ID from GitHub.
Please let me know if you have any questions.

**Comment by eshupps** [comment]
1. Please provide more information on the failing API Properties Validator error. There is no definition for "scriptOperations" in the API Properties schema (https://github.com/microsoft/PowerPlatformConnectors/blob/dev/schemas/paconn-apiProperties.schema.json) nor could I find any reference to it in the documentation. What does this error refer to?
2. The API properties validator is failing a check indicating that an enum value has changed; however, that is the exact value you requested that I change for this PR ("Turkey" to "Republic of Türkiye"). It seems strange to block my PR for a change you requested I make. Also, the second failure is for a bug fix where the wrong type of output was previously being specified, causing some operations to fail, so it is a necessary change.

**Comment by eshupps** [comment]
@Amjed-Ayoub Regarding the separate PR's, only the PRO connector has a reference to "Turkey" that needed to be changed, the LITE connector does not so no update necessary.

**Comment by Amjed-Ayoub** [comment]
@eshupps please update your branch, you are making changes to another connector. 
image

**Comment by eshupps** [comment]
Something odd has happened again, similar to the last PR we submitted. I copied the updated files only into our connector folder, then added them to the branch and committed. Below you can see my git commands and the associated local path. When I look at the ServiceDesk connector in my local files, it has the proper files (theirs, not ours). If you look at my repo in commit 68b3637 (https://github.com/microsoft/PowerPlatformConnectors/commit/68b36377d752e848c0befa3caf167cbf3f4ccab6) you'll see only my changes, yet somehow the ServiceDesk changes from their commit d36b5d4 (https://github.com/microsoft/PowerPlatformConnectors/commit/d36b5d4fa72affdd4eb811f7e1f49bad85d58894) also got included in my PR. This happened before and you did something on your side to fix it. I don't know what I can do to solve it, other than try rolling it all back and doing a new commit.

Screenshot 2023-05-16 at 9 24 13 AM

**Comment by Amjed-Ayoub** [comment]
@eshupps Please close this PR. if updating the branch is not working, then maybe create a new fork and submit again.

**Comment by eshupps** [comment]
Closing per request.

**Pull request closed without merging**
