### PR TITLE
Square Business (Independent Publisher) v1.2

### PR DESCRIPTION
**Pull request by troystaylor**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [X] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [X] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by v-EgorKozhadei** [comment]
[[certify-connector]]

**Comment by v-EgorKozhadei** [comment]
[[certify-connector]]

**Comment by v-EgorKozhadei** [comment]
Hello @troystaylor, 

I hope you are doing well. 

Congratulations, your connector is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.  

Please let us know if you have any questions. 

Thank you very much for working with us.

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor,
I hope you are doing well.
Your connector is in production deployment and queued up for the next deployment schedule. This process typically takes 3-4 weeks. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps.
Please let us know if you have any questions.
Thank you very much for working with us.

**Review by sriyen-msft — APPROVED** [review]

**Comment by sriyen-msft** [comment]
@troystaylor Apologies for the delay in response. 

Congratulations! The deployment of your connector and documentation page is now complete, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program, Thanks.

**Comment by vmanoharas** [comment]
Hi @troystaylor, 

Our localization team identified errors during the localization process. Some strings exceed the allowed limit and need to be shortened. Please ensure these strings are within 500 characters. Kindly review and update them accordingly and resubmit the PR for certification. 

We sincerely appreciate your help in this regard.

line [1428]:"description": "The URL to redirect to after checkout is completed with checkoutId, Square's orderId, transactionId, and referenceId appended as URL parameters. For example, if the provided redirect_url is http://www.example.com/order-complete, a successful transaction redirects the customer to: <pre><code>[http://www.example.com/order-complete?checkoutId=xxxxxx&orderId=xxxxxx&referenceId=xxxxxx&transactionId=xxxxxx</code></pre>](http://www.example.com/order-complete?checkoutId=xxxxxx&orderId=xxxxxx&referenceId=xxxxxx&transactionId=xxxxxx%3C/code%3E%3C/pre%3E) If you do not provide a redirect URL, Square Checkout will display an order confirmation page on your behalf; however Square strongly recommends that you provide a redirect URL so you can verify the transaction results and finalize the order through your existing/normal confirmation workflow.",
line [1820]:"description": " For example, if the provided redirect URL is http://www.example.com/order-complete, a successful transaction redirects the customer to: <pre><code>[http://www.example.com/order-complete?checkoutId=xxxxxx&referenceId=xxxxxx&transactionId=xxxxxx</code></pre>](http://www.example.com/order-complete?checkoutId=xxxxxx&referenceId=xxxxxx&transactionId=xxxxxx%3C/code%3E%3C/pre%3E) If you do not provide a redirect URL, Square Checkout displays an order confirmation page on your behalf; however, it is strongly recommended that you provide a redirect URL so you can verify the transaction results and finalize the order through your existing/normal confirmation workflow.",
 
line[8797]:  "scopes": {
        "BANK_ACCOUNTS_READ CASH_DRAWER_READ CUSTOMERS_READ CUSTOMERS_WRITE DEVICE_CREDENTIAL_MANAGEMENT EMPLOYEES_READ EMPLOYEES_WRITE INVENTORY_READ INVENTORY_WRITE ITEMS_READ ITEMS_WRITE LOYALTY_READ LOYALTY_WRITE MERCHANT_PROFILE_READ ORDERS_READ ORDERS_WRITE PAYMENTS_READ PAYMENTS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS PAYMENTS_WRITE_IN_PERSON SETTLEMENTS_READ TIMECARDS_READ TIMECARDS_WRITE TIMECARDS_SETTINGS_READ TIMECARDS_SETTINGS_WRITE APPOINTMENTS_READ APPOINTMENTS_WRITE APPOINTMENTS_BUSINESS_SETTINGS_READ INVOICES_READ INVOICES_WRITE SUBSCRIPTIONS_READ SUBSCRIPTIONS_WRITE DISPUTES_READ DISPUTES_WRITE GIFTCARDS_READ GIFTCARDS_WRITE ONLINE_STORE_SNIPPETS_WRITE ONLINE_STORE_SNIPPETS_READ ONLINE_STORE_SITE_READ PAYMENTS_WRITE_SHARED_ONFILE": "BANK_ACCOUNTS_READ CASH_DRAWER_READ CUSTOMERS_READ CUSTOMERS_WRITE DEVICE_CREDENTIAL_MANAGEMENT EMPLOYEES_READ EMPLOYEES_WRITE INVENTORY_READ INVENTORY_WRITE ITEMS_READ ITEMS_WRITE LOYALTY_READ LOYALTY_WRITE MERCHANT_PROFILE_READ ORDERS_READ ORDERS_WRITE PAYMENTS_READ PAYMENTS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS PAYMENTS_WRITE_IN_PERSON SETTLEMENTS_READ TIMECARDS_READ TIMECARDS_WRITE TIMECARDS_SETTINGS_READ TIMECARDS_SETTINGS_WRITE APPOINTMENTS_READ APPOINTMENTS_WRITE APPOINTMENTS_BUSINESS_SETTINGS_READ INVOICES_READ INVOICES_WRITE SUBSCRIPTIONS_READ SUBSCRIPTIONS_WRITE DISPUTES_READ DISPUTES_WRITE GIFTCARDS_READ GIFTCARDS_WRITE ONLINE_STORE_SNIPPETS_WRITE ONLINE_STORE_SNIPPETS_READ ONLINE_STORE_SITE_READ PAYMENTS_WRITE_SHARED_ONFILE"
      }
line[8804]: "security": [
    {
      "oauth2_auth": [
        "BANK_ACCOUNTS_READ CASH_DRAWER_READ CUSTOMERS_READ CUSTOMERS_WRITE DEVICE_CREDENTIAL_MANAGEMENT EMPLOYEES_READ EMPLOYEES_WRITE INVENTORY_READ INVENTORY_WRITE ITEMS_READ ITEMS_WRITE LOYALTY_READ LOYALTY_WRITE MERCHANT_PROFILE_READ ORDERS_READ ORDERS_WRITE PAYMENTS_READ PAYMENTS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS PAYMENTS_WRITE_IN_PERSON SETTLEMENTS_READ TIMECARDS_READ TIMECARDS_WRITE TIMECARDS_SETTINGS_READ TIMECARDS_SETTINGS_WRITE APPOINTMENTS_READ APPOINTMENTS_WRITE APPOINTMENTS_BUSINESS_SETTINGS_READ INVOICES_READ INVOICES_WRITE SUBSCRIPTIONS_READ SUBSCRIPTIONS_WRITE DISPUTES_READ DISPUTES_WRITE GIFTCARDS_READ GIFTCARDS_WRITE ONLINE_STORE_SNIPPETS_WRITE ONLINE_STORE_SNIPPETS_READ ONLINE_STORE_SITE_READ PAYMENTS_WRITE_SHARED_ONFILE"
      ]
    }
  ],

line[1428]:"description": "The URL to redirect to after checkout is completed with checkoutId, Square's orderId, transactionId, and referenceId appended as URL parameters. For example, if the provided redirect_url is http://www.example.com/order-complete, a successful transaction redirects the customer to: <pre><code>[http://www.example.com/order-complete?checkoutId=xxxxxx&orderId=xxxxxx&referenceId=xxxxxx&transactionId=xxxxxx</code></pre>](http://www.example.com/order-complete?checkoutId=xxxxxx&orderId=xxxxxx&referenceId=xxxxxx&transactionId=xxxxxx%3C/code%3E%3C/pre%3E) If you do not provide a redirect URL, Square Checkout will display an order confirmation page on your behalf; however Square strongly recommends that you provide a redirect URL so you can verify the transaction results and finalize the order through your existing/normal confirmation workflow.",

**Pull request merged**
