### PR TITLE
App Store Connect (Independent Publisher)

### PR DESCRIPTION
**Pull request by developer-farhan**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [✅  ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ ✅ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ✅ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ✅ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ✅ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ✅ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ✅ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ✅ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ✅ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [✅  ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

# `2 Unique Operations`
List Apps - Validation
Read App Information Validation

# `Test Operation Section`
Test Section Validated

# `Paconn Validation`
ASC-Validated

# `Solution Checker Validation`
ASC Solution Checker Validation

# Personal Opinion
#### My Custom Connector is/will be one of the most powerful connectors available. With my connector, you can seamlessly integrate the Apple development environment with the Microsoft development tools, enhancing the user experience and reaching a wider audience. My connector is a product of my passion and vision for this field, and it has enormous potential to transform the app industry.

### CODE REVIEW

**Review by vmanoharas — APPROVED** [review]
Hello @officialFlutterDeveloper 
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by developer-farhan** [comment]
@vmanoharas As always its an honour. I really enjoyed working with Microsoft last time, and it inspired me to start the next project as soon as my last one got approved. It's a great honor and a lot of fun to work with Microsoft. I believe my work, especially this new connector, will drive business value to Microsoft

**Comment by troystaylor** [comment]
@officialFlutterDeveloper Congratulations on the certification of your connector.
@vmanoharas @ShefaaliP Can you please confirm that the JWT method of authentication is allowed? There is no custom code that creates the token and none of the mentioned libraries work directly with Power Platform. Previous connectors using a token with an external dependency have not been certified.

**Comment by developer-farhan** [comment]
@vmanoharas Requesting progress on the deployment and wanting to know when will my connectors be listed [here](https://learn.microsoft.com/en-us/connectors/connector-reference/) thank you :)

**Comment by vmanoharas** [comment]
Hello Partner,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short survey on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Comment by developer-farhan** [comment]
> Hello Partner, I hope you are doing well. Congratulations, the deployment of your connector and documentation page was already completed, We have a short survey on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program. Thank you very much for working with us.

I would be happy to complete the survey.

**Pull request merged**
