### PR TITLE
Added Actions to Request a Team using the Teams-Spirit Connector

### PR DESCRIPTION
**Pull request by ghost**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] ~I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. ~
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

### CODE REVIEW

**Comment by vmanoharas** [comment]
Hello @tillkaemmerer, 

Thank you very much for new PR. 

Can you please check Swagger validation error checks? there are many code breaking changes.  Please check and confirm that the existing flows are breaking or not? if existing flows are breaking, please fix them.

**Review by ghost — COMMENTED** [review]
Fixed Validation Issues

**Comment by ghost** [comment]
> Hello @tillkaemmerer,
> 
> Thank you very much for new PR.
> 
> Can you please check Swagger validation error checks? there are many code breaking changes. Please check and confirm that the existing flows are breaking or not? if existing flows are breaking, please fix them.

@vmanoharas  As far as I can see, the only change that lead to a validation error, was the `oAuthSettings.redirectMode` in the API Properties, which was set from "Global" to "GlobalPerConnector". I changed it back to "Global" now.

The changes in the swagger file itself are only additions ("Request a  Team" and "Get Templates")  and a visibility change for "Get all Tags"), thus there should no breaking changes and the new functions were also added an tested with existing flows. 

As for the rest of API Properties, it seems that the git diff is a bit misleading. I don't know why it is displaying that many changes, but the only actual change is the `clientId` where the placeholder format was changed. This will not affect existing flows, because the placeholder will be filled on rollout and since the value itself won't change, there won't be any effect on the connectors behaviour.

**Comment by ghost** [comment]
@vmanoharas Is it possible, that some validation errors do not come from our connector? For example there is an error which states

``Existing flows may be broken if they are using this field and actual payload has been changed. ValuePath: operation/PublicAPI-getItem/responses/200/schema/internal_contacts/items/type/type Source: NewSwagger``

However we do not have a schema containing `internal_contacts`. The only schema containing that value is in `certified-connectors/Bloomflow`, which was is not changed by this PR.

**Comment by vmanoharas** [comment]
Hello @tillkaemmerer, 

Yes, thanks for bringing this up.  However, it seems your commit not from your fork, it is included other connectors fork as well.  Please see below screenshot.  Could you please close this PR and merge to main branch from your fork branch?

image

**Pull request closed without merging**
