### PR TITLE
Added new actions, new optional parameters, tweaked some descriptions 

### PR DESCRIPTION
**Pull request by Blackbaud-BenLambert**
---
Please check the following conditions for your PR.

- [ ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Comment by dougelliott** [comment]
@Blackbaud-BenLambert Going forward we're asking partners to make PRs to the `dev` branch first, then we will handle getting those changes merged into master for them. Would you be able to re-create the PR for these changes into the dev branch?

**Comment by dougelliott** [comment]
@Blackbaud-BenLambert Checking in on the above comment

**Review by mamurshe — APPROVED** [review]

**Comment by mamurshe** [comment]
> @Blackbaud-BenLambert Checking in on the above comment

Waiting on this.

**Comment by Blackbaud-BenLambert** [comment]
@dougelliott @mamurshe sorry for the delay, been out for a few weeks moving out of state.  Looks like this PR is closed - anything you still need me to do?  Going forward, I'll send PRs to the `dev` branch.

**Comment by dougelliott** [comment]
@Blackbaud-BenLambert Hope the move went well! All is good now, but yes, please do future PRs to the `dev` branch. Have a great weekend ahead.

**Pull request merged**
