### PR TITLE
Encodian Sept 23 Release

### PR DESCRIPTION
**Pull request by Encodian**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

Please note there has been a process issue here, the following pull request was never completed: https://github.com/microsoft/PowerPlatformConnectors/pull/2775 

But... the changes have been deployed, this this PR now includes changes which have actually already been deployed by Microsoft to Power Automate.

Please progress with the approval / deployment to the preview environment and we will complete a final validation.

### CODE REVIEW

**Comment by Encodian** [comment]
The three errors regarding the actions which have been hidden... have already been deployed with the July release, they are live in Power Automate!

**Comment by vmanoharas** [comment]
Hello @Encodian, 

Can you please review Swagger validation checker errors and confirm that due to new changes the existing flows will not break?

**Comment by Encodian** [comment]
> Hello @Encodian,
> 
> Can you please review Swagger validation checker errors and confirm that due to new changes the existing flows will not break?

Yes, please refer to my message last week when I raised the PR.

These swagger elements generating these errors have already been deployed to Power Automate last month... for some reason the last PR wasn't completed but the release did happen via isv.studio 

Anyhow, yes the definition is correct please proceed.

**Comment by Encodian** [comment]
Closing this PR as we are going to include another change into the release

**Pull request closed without merging**
