### PR TITLE
Update ForceManager CRM connector (bug fixes + add new actions and triggers)

### PR DESCRIPTION
**Pull request by r4m**

### CODE REVIEW

**Comment by vmanoharas** [comment]
Hello @r4m, 

Seems like you have closed two PRs and opened this one, this PR seems to be ok, I will approve it, please follow the steps that I have posted below.

**Review by vmanoharas — APPROVED** [review]
Hello @r4m 
I hope you are doing well.
Congratulations, your pull request is approved and merged. Please [submit the files to ISV Studio](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) or [update your submission](https://learn.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#update-submission-prior-to-certification) using your latest commit ID, please allow us up to 1-2 weeks to review your submission, and our Engineers will notify you in the “Activity Control” area in ISV Studio. Please [make sure that the icon meets all the requirements](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-submission#design-an-icon-for-your-connector), that it’s size is 230x230, icon background is not white or transparent and it matches the iconBrandColor property in apiProperties.json file.
After making the submission in ISV Studio, please attach an intro.md file in the activity control section. This file is required and it's different from readme.md. You can [find an example of intro.md file on this page](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) at step 6.
Please [Create an environment in the Preview region](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#create-an-environment-in-the-preview-region). You will use this environment later to [test your connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#test-your-connector) after Microsoft is done with the functional verification for your connector.
We expect all tests to be completed within 1-2 weeks.
If your connector passes all tests, the deployment process begins, and it typically takes up to 3 to 4 weeks to deploy your connector to all of our regions.
Please let me know if you have any questions or run into any problems while creating or updating your submission.
Thank you very much for working with us.

**Comment by r4m** [comment]
hi @vmanoharas yes but can you also **delete** the other closed PR? They were wrongly containing sensible data.

**Comment by vmanoharas** [comment]
Hey @r4m, Unfortunately, I dont have option to delete the PR. Apologies for the same.

**Comment by r4m** [comment]
ok @vmanoharas thanks, do you eventually know which person here is an admin?

**Comment by troystaylor** [comment]
@r4m Repo owners cannot delete the PR. You would have to contact GitHub Support for that: https://support.github.com/request

**Comment by r4m** [comment]
@troystaylor thanks for replying, I contacted Github Support but they told me this:

> For privacy and security reasons, only a repository admin can authorize the deletion of a pull request.
>  
> If you're able to get in touch with an admin directly, you could forward them the email version of this message and ask them to reply (from an email address associated with their GitHub account) giving us authorization. They could also reach out to us directly in a new ticket they create themselves, if that's easier.
>  
> If you're not able to contact an admin of that repository, please take a look at the following article for information about how to submit a content removal request:
>  
> [Submitting content removal requests](https://docs.github.com/en/github/site-policy/submitting-content-removal-requests)

Do you suggest me to proceed with submitting a content removal request?

**Comment by troystaylor** [comment]
@r4m Yes, please submit the content removal request.

**Comment by r4m** [comment]
ok, I tried @troystaylor but the process only allow to submit specific files from what I can see [here](https://support.github.com/contact/private-information) no PR urls :/ and I don't think I can specifically report a url of a file inside a PR, can't I?

**Pull request merged**
