### PR TITLE
Update Publisher Edatalia Sign Online

### PR DESCRIPTION
**Pull request by marpedroche**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Review by marpedroche — COMMENTED** [review]
@microsoft-github-policy-service agree company="Axazure"

**Review by vmanoharas — COMMENTED** [review]
Hello @marpedroche, 

Why the image folder you kept it separate, and kindly let me know what is the purpose of keeping it separate and the purpose. 

image

**Comment by marpedroche** [comment]
@vmanoharas This folder was in the previously validated branch. I updated the Publisher and replaced the logo with the new image. The 'img' folder is used to store the image used in the README file.

**Review by vmanoharas — DISMISSED** [review]
Hello @marpedroche 
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by vmanoharas** [comment]
Hello @marpedroche, 

Separate img folder will stop uploading your files into our internal tools, as per the guidelines, Independent publisher should have only one folder, kindly include image also inside the main folder.

**Comment by marpedroche** [comment]
@vmanoharas, I see that you approve the PR, please let me know if I have to change the images to the main folder.

**Comment by vmanoharas** [comment]
> @vmanoharas, I see that you approve the PR, please let me know if I have to change the images to the main folder.

Yes @marpedroche, kindly update as requested as our automation tool will not run to upload artifacts into our internal tool.

**Comment by marpedroche** [comment]
@vmanoharas update done! I removed all the folders and put the images in the mail folder.

**Comment by vmanoharas** [comment]
Your connector artifacts will not be uploaded into our internal tool, as Independent Publishers should not have any files other than apiDifinition.swagger.json, apiProperties.json and readme.md files. kindly submit only these files, and attach other files in the comments section, we will take care of during certification process. 

Apologies for the inconvenience caused, thank your patience and understanding.

**Comment by marpedroche** [comment]
@vmanoharas these images you see are used in the readme file.

**Comment by vmanoharas** [comment]
> @vmanoharas these images you see are used in the readme file.

Hello @marpedroche, 

Thank you very much for your quick response, however as per the process and the tool images are not allowed in the artifacts folder. In other words this is a blocker to proceed further.

**Comment by vmanoharas** [comment]
Hello @marpedroche, 

Kindly attach images here in the comments section and keep only three files (apiDifinition.swagger.json, apiProperties.json and readme.md).  Our engineering team will take these images while processing your connector.

**Comment by marpedroche** [comment]
@vmanoharas Please find the attached image. These items have already been removed from the repository.

APIKey
AxazureLogo
Connexion
integrationAPI
WebhookUrl

**Comment by vmanoharas** [comment]
Hello @marpedroche, 

Please see the screenshot below, still we can see all the images which you deleted and added.  Kindly close this PR and open a new PR with only three files mentioned above. 

image

**Pull request closed without merging**
