### PR TITLE
Connect2All: changed host name

### PR DESCRIPTION
**Pull request by GAC-AJO**
We now use a gateway so we needed to change the host name.

### CODE REVIEW

**Comment by v-EgorKozhadei** [comment]
Hello @GAC-AJO,

There's a conflict between branches, please see the error message below.
Please make sure that your branch is up-to-date and contains the latest changes.

Let us know if you have any questions.

**Comment by GAC-AJO** [comment]
Hello @v-EgorKozhadei ,

I thought it was necessary to increase the version number. 
I have now turned the number back to 2.4.

**Comment by v-EgorKozhadei** [comment]
Hello @GAC-AJO,

You can increase it with updating the files, but please make sure that there's no conflict when creating a PR.

I can see that your branch is 19 commits behind open source repository's dev branch. You need to pull the latest changes first, then make changes to connector files, e.g. version or any other changes.

Please let us know if you have any questions.

**Review by v-EgorKozhadei — APPROVED** [review]

**Comment by v-EgorKozhadei** [comment]
Hello @GAC-AJO, 

I hope you are doing well. 

Congratulations, your pull request is approved and merged. Please [submit the files to ISV Studio](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) or [update your submission](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-updates) using your latest commit ID, please allow us up to 1-2 weeks to review your submission, and our Engineers will notify you in the “Activity Control” area in ISV Studio. Please [make sure that the icon meets all the requirements](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-submission#design-an-icon-for-your-connector), that it’s size is 230x230, icon background is not white or transparent and it matches the iconBrandColor property in apiProperties.json file. 

After making the submission in ISV Studio, please attach an intro.md file in the activity control section. This file is required and it's different from readme.md. You can [find an example of intro.md file on this page](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) at step 6. 

Please [Create an environment in the Preview region](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#create-an-environment-in-the-preview-region). You will use this environment later to [test your connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#test-your-connector) after Microsoft is done with the functional verification for your connector.  

We expect all tests to be completed within 1-2 weeks. 

If your connector passes all tests, the deployment process begins, and it typically takes up to 3 to 4 weeks to deploy your connector to all of our regions. 

Please let me know if you have any questions or run into any problems while creating or updating your submission. 

Thank you very much for working with us.

**Pull request merged**
