### PR TITLE
PowerTools Lite v2-0

### PR DESCRIPTION
**Pull request by eshupps**
Update PowerTools LITE to version 2.0
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ x] I attest that the connector ~~doesn't exist on the Power Platform today~~ is a new version of an existing connector. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by v-EgorKozhadei** [comment]
Hello @eshupps,

Your PR affects other connectors' files. Please make sure that your branch is up-to-date and contains the latest changes.
The PR should contain only your connector files.

Let us know if you have any questions.

**Comment by v-EgorKozhadei** [comment]
Hello @eshupps,

I checked your branch before the PR was closed, it was 64 commits behind our dev branch. I'd suggest fetching the latest changes to your fork or recreating the fork to resolve the issue quickly.
If the issue arises again, we will take a look at why other connector commit got included in your PR.

**Comment by eshupps** [comment]
I deleted my repository and created an entirely new fork. Went through all the steps again and the b468154 commit from 5-Aug is still being included with mine. Is there a command I can run to exclude these commits from my PR?

**Comment by v-EgorKozhadei** [comment]
@eshupps,

Thank you for you message!

Please try [reverting the changes](https://www.atlassian.com/git/tutorials/undoing-changes/git-revert#:~:text=The%20git%20revert%20command%20is,ref%20pointers%20to%20this%20commit.) for your branch by using the `git revert <commit ref>`.

We will take a look into that. Could you please provide a bit more information about how you created your fork? You created it from our dev branch, right?

**Comment by eshupps** [comment]
Yes, that's correct - fork created from dev branch. I then cloned it local and walked through the steps as follows:

git remote -v
git remote add upstream https://github.com/microsoft/PowerPlatformConnectors.git
git fetch upstream
git checkout master 
git merge upstream/master

Then I created a new branch:

git switch -c PowerToolsLITE_v3-0

Copied my updated files to the PowerToolsLITE folder, switched to that folder then did the following:

git add .
git commit
git push -u --set-upstream origin PowerToolsLITE_v3-0

**Comment by v-EgorKozhadei** [comment]
Hello @eshupps,

Thank you for your message!

I found out what is causing the issue. We will work on fixing it, sorry for the inconvenience!

Could you please try doing `git status` after copying updated files and switching to the folder?
If you see other connector changes and your folder (should be visible as `./` or just file names without slash sign), just add your changes (`git add ./` or `git add filename1 filename2 etc` when in connector folder). After that commit the changes to your branch. The pull request should contain only your files after that.

Please let us know if you have any questions or run into any issue!

**Comment by eshupps** [comment]
Went through the process again and 'git status' showed only my changes. I tried adding the files individually but the results were the same. I will wait for the fix before attempting another push. Thanks for all the help!

**Comment by v-EgorKozhadei** [comment]
Hello @eshupps,

We have fixed the issue. Could you please try recreating the fork and opening a new PR? Everything should be fine now.

Please let us know if there are any issues!

**Comment by eshupps** [comment]
New PR submitted. Looks much better this time. Thank you!

**Pull request closed without merging**
