### PR TITLE
 FCA (Independent Publisher) Connector - Added and Updated Actions

### PR DESCRIPTION
**Pull request by gulshankhurana**
- Fixed the 'Common Search' action.
- Added 'Find Firm Details' and 'Find Product Details' actions.

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

Con-Def

Con-Test-CommonSearch-Individual

Con-Test-CommonSearch-Fund

Con-Test-CommonSearch-Firm

Con-Test-FirmDetails

Con-Test-ProductDetails

Flow-CommonSearch-Individual

Flow-CommonSearch-Firm

Flow-CommonSearch-Fund

Flow-FindFirmDetailsByFRN

Flow-FindProductDetailsByPRN

### CODE REVIEW

**Review by gulshankhurana — COMMENTED** [review]
@vmanoharas , I've closed #3495 and created a new pull request. Please could you review this and let me know if it's ok. BTW, when I ran validation check on the swagger file using paconn validate comand, it succeeded with warnings.

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, 

Thank you for submitting a new PR. However you have merged this PR too, kindly don't merge it until the review completes. Additionally the is still in progress state, please change it. 

image

image

**Comment by gulshankhurana** [comment]
@vmanoharas , it is ready for review again. Thanks.

**Review by vmanoharas — DISMISSED** [review]
Hello @gulshankhurana 
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by gulshankhurana** [comment]
@vmanoharas , thanks for your patience. 
Question: How can I track the usage stats for my connector?

Thanks.
Kind regards
Gulshan

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, 

Your connector artifacts have not been uploaded into our internal tool after multiple attempts, as you have modified the title of the connector. Modifying title is not allowed for Independent Publisher, kindly submit new connector with new version. Apologies for the inconvenience caused. 

Thanks for your patience and understanding.

**Comment by gulshankhurana** [comment]
@vmanoharas, I have changed the name back to FCA as it was originally. Hopefully, this should go through fine now?

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by gulshankhurana** [comment]
@vmanoharas , please could you review this. Thanks.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, 

Please accept my apologies, I thought I have reviewed and approved this PR already. Unfortunately, old name is also not accepted. Last time we had same issue so we have taken files from here manually and certified.  Please see the validation error below and correct the title. 

image

**Comment by gulshankhurana** [comment]
> Hello @gulshankhurana,
> 
> Please accept my apologies, I thought I have reviewed and approved this PR already. Unfortunately, old name is also not accepted. Last time we had same issue so we have taken files from here manually and certified. Please see the validation error below and correct the title.
> 
> image

If only I knew what it meant, it's all like a foreign language to me. I don't know where the error is, let alone knowing how to resolve this :(

What would the quickest/easiest way for a non-dev like me to get my request approved? Start afresh with new pull request and fresh submission?
@vmanoharas

**Comment by vmanoharas** [comment]
> > Hello @gulshankhurana,
> > Please accept my apologies, I thought I have reviewed and approved this PR already. Unfortunately, old name is also not accepted. Last time we had same issue so we have taken files from here manually and certified. Please see the validation error below and correct the title.
> > image
> 
> If only I knew what it meant, it's all like a foreign language to me. I don't know where the error is, let alone knowing how to resolve this :(
> 
> What would the quickest/easiest way for a non-dev like me to get my request approved? Start afresh with new pull request and fresh submission? @vmanoharas

Hello @gulshankhurana, 

If you understand the error mentioned in the image below, the title should not be like all uppercase or lower case, it should be as per the example below. 

-- AsHashTable

image

**Comment by gulshankhurana** [comment]
@vmanoharas , thanks for the prompt response. I really appreciate that.
Originally, the title was "FCA" only which I changed to "Financial Conduct Authority UK" but it was agaisnt the system rules to change the name so I changed it back to "FCA" and now you're saying that the system doesn't accept all capital letters but it did originally. Since "FCA" is an abbreviation so I can't/mustn't change it to "Fca".

What do you propose I should do? If possible, I'd rather go for the name "Financial Conduct Authority UK" as this is what the connector is all about.

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, 

Sorry for lot of confusions created, we will go ahead with FCA now, and let's decide next time. As our certification process is going to change soon. I will request our engineers to take the files from here and certify it.

**Review by vmanoharas — DISMISSED** [review]
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by gulshankhurana** [comment]
@vmanoharas, Thanks again for all your help. 
Please advise how can I track the usage stats for my connector?

**Comment by vmanoharas** [comment]
> @vmanoharas, Thanks again for all your help. Please advise how can I track the usage stats for my connector?

@gulshankhurana, unfortunately, you cannot track as an Independent Publisher.

**Comment by gulshankhurana** [comment]
Hi @vmanoharas 

Any luck progressing it to the deployment stage?

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, Yes, your connector was included in last week's deployment cycle and is expected to be completed within the next 2-3 weeks.

**Comment by gulshankhurana** [comment]
Hi @vmanoharas 

Any further updates on deployment completion date?

**Comment by vmanoharas** [comment]
> Hi @vmanoharas
> 
> Any further updates on deployment completion date?

Hi @gulshankhurana, 

your connector is being deployed, it may approximately complete in another 5 to 6 working days.

**Comment by gulshankhurana** [comment]
@vmanoharas , I've just created a new PR #3547 and wondering if this would delay the deployment of my existing (already approved) #3500 PR which is already included in the deployment schedule as confirmed by you last week.

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, 

Your new changes in this PR https://github.com/microsoft/PowerPlatformConnectors/pull/3547 will be approved and included after your current version of the connector deployed to all regions.

**Comment by gulshankhurana** [comment]
> Hello @gulshankhurana,
> 
> Your new changes in this PR #3547 will be approved and included after your current version of the connector deployed to all regions.

Thank @vmanoharas. Eagerly waiting for FCA connector update to be deployed.

**Comment by gulshankhurana** [comment]
Hi @vmanoharas, it's been 5 weeks now since you approved the changes to the FCA Connector. Are there any updates regarding deployment yet? Thanks.

**Comment by vmanoharas** [comment]
> Hi @vmanoharas, it's been 5 weeks now since you approved the changes to the FCA Connector. Are there any updates regarding deployment yet? Thanks.

Hi @gulshankhurana, Apologies for the delay in deploying your connector, now your connector is deployed to last but one region, it will be completed by early next week. 

Thank you for your patience and understanding.

**Comment by gulshankhurana** [comment]
> > Hi @vmanoharas, it's been 5 weeks now since you approved the changes to the FCA Connector. Are there any updates regarding deployment yet? Thanks.
> 
> Hi @gulshankhurana, Apologies for the delay in deploying your connector, now your connector is deployed to last but one region, it will be completed by early next week.
> 
> Thank you for your patience and understanding.

Hi @vmanoharas 

Another week gone, still waiting :(

**Comment by vmanoharas** [comment]
Hello @gulshankhurana ,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Review by vmanoharas — APPROVED** [review]
Hello Partner,
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks. 
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
Hello @gulshankhurana ,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Pull request merged**
