### PR TITLE
Cleanup of fields and resolved comments

### PR DESCRIPTION
**Pull request by RalphNoordanus**
---
Please check the following conditions for your PR.

- [ ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Comment by RalphNoordanus** [comment]
@sriyen-msft could you contact me regarding our connector, my contact Doug Elliott is gone away, get a email delivery failure when contacting him.

**Comment by RalphNoordanus** [comment]
@sriyen-msft, Is there anything we could do to for this Pull Request. I see failing Swagger and Change Validation. I'm worried this pull request is "forgotten".

**Comment by sriyen-msft** [comment]
> @sriyen-msft, Is there anything we could do to for this Pull Request. I see failing Swagger and Change Validation. I'm worried this pull request is "forgotten".

Please ignore Swagger and Change Validation errors reported in this PR as your connector is brand new and never certified. These errors reports the breaking changes if the connector if it exists in the production regions.

**Comment by sriyen-msft** [comment]
> @sriyen-msft could you contact me regarding our connector, my contact Doug Elliott is gone away, get a email delivery failure when contacting him.

You can reach out to our team's email address (ConnectorPartnerMgmtTeam@service.microsoft.com) if you have any questions.

**Review by sriyen-msft — APPROVED** [review]

**Pull request merged**
