### PR TITLE
OpenAI GPT4 (Addition of Whisper API to Troy Taylor's connector) (Independent Publisher) 

### PR DESCRIPTION
**Pull request by PriyaranjanKS**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

# Proposal - <Whisper Open AI> (Independent Publisher)

This is an addition to the Open AI connector by Troy Taylor . The proposed additional endpoint leverages the Whisper Open AI to perform robust audio processing, providing functionalities for transcribing and translating audio to text.

### Transcribe Audio

This action allows the transcription of audio into text, providing a convenient method to convert spoken words within an audio file into written text for various applications.

### Translate Audio

This action allows the translation of audio from any language to english language text

# Implementations

Screenshots of the implementation are as below : 

## Actions without Parameters
WithoutParameters

## Actions with Parameters
WithParameters

## Output in Power Automate Designer
Output

## Output in Customer Connector Creation Phase
Since the Test window do not allow file uploading, sharing the output from Swagger test section 
SwaggerTest

### CODE REVIEW

**Review by PriyaranjanKS — COMMENTED** [review]
Updated the files with additional endpoint and details

**Comment by PriyaranjanKS** [comment]
Hi @vmanoharas , We have 2 Open AI connectors . One from Troy Taylor and another one from Robin Rosengrün. So I have updated both the connectors with the addition of Whisper API and have tested existing functionalities for breaking changes.

**Comment by PriyaranjanKS** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by vmanoharas** [comment]
Hi @PriyaranjanKS, Thank you very much for submitting this.  

@troystaylor - can you please provide approval to proceed further? As you are the owner of this connector.

**Comment by PriyaranjanKS** [comment]
> Hi @PriyaranjanKS, Thank you very much for submitting this.
> 
> @troystaylor - can you please provide approval to proceed further? As you are the owner of this connector.

Being a first time submitter, I was not sure about getting approvals from original publisher. Apologies, requesting your approval @troystaylor

**Comment by vmanoharas** [comment]
Hello @troystaylor, requesting your approval to proceed further.

**Comment by troystaylor** [comment]
Due to the status of my previous update being still on the deployment train and this week's API updates, I'm going to reject this PR as my next update will have these actions and it will be released sooner from my branch.

**Comment by vmanoharas** [comment]
Thank you very much @troystaylor for the update. 

@PriyaranjanKS, I am closing this PR as per @troystaylor comment above.

**Pull request closed without merging**
