### PR TITLE
Changed Converter Connector

### PR DESCRIPTION
**Pull request by stsiek**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by stsiek** [comment]
Please merge this changes, we changed the name of the connector after testing.

**Review by v-EgorKozhadei — COMMENTED** [review]
Hi @stsiek! Please remove the intro.md file from the PR and completely remove Converter folder or rename it to your current folder name. There should be only one folder with your connector. We'll be able to approve and merge the PR after this minor fix, thank you!

**Comment by stsiek** [comment]
Hi

**Comment by stsiek** [comment]
Hi, thanks for you feedback. i deleted the intro.md but i can't find the converter folder. i renamed it yesterday to "converter by power2apps" and now it looks like there is a conflict. could you help me to solve it?

**Comment by v-EgorKozhadei** [comment]
Hi @stsiek! I think that the fastest option is to [create a new fork](https://github.com/microsoft/PowerPlatformConnectors#creating-a-fork), add your updated files to a new folder, remove the old folder and open a new PR. Before creating a new fork you may need to delete the existing one, it can be done in the fork's settings.

Please let us know if you have any questions or need help!

**Pull request closed without merging**
