### PR TITLE
Added UiPath PA Connector

### PR DESCRIPTION
**Pull request by GitRob77**
Initial release of the UiPath Power Automate Connector.

Co-Authored-By: TuckermanRav <9101094+tuckermanrav@users.noreply.github.com>

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by natalie-pienkowska** [comment]
Hi @GitRob77 thanks for your submission! 

We just want to confirm whether this is an Independent Publisher connector or not, especially since the Publisher is listed as UIPath. Do you work at UIPath? If not, this would be an Independent Publisher connector and the Publisher should be you and your colleague's name, while the StackOwner would be UIPath. 

Also, I noticed that you wrote this would be private preview of the connector. Do you mind providing more context?

**Comment by GitRob77** [comment]
Hi Natalie!
Thank you for your message!

Yes, I am a product manager here at UiPath and I am working on platform integrations. So the plan is to launch this as official UiPath Connector for Power Automate.
We want to deploy the connector as private preview first, so we can collect feedback from customers before we launch it officially.

BR
Robert

**Comment by sriyen-msft** [comment]
> Hi Natalie! Thank you for your message! Yes, I am a product manager here at UiPath and I am working on platform integrations. So the plan is to launch this as official UiPath Connector for Power Automate. We want to deploy the connector as private preview first, so we can collect feedback from customers before we launch it officially. BR Robert From: natalie-pienkowska ***@***.***> Sent: Dienstag, 7. Dezember 2021 20:52 To: microsoft/PowerPlatformConnectors ***@***.***> Cc: Robert Wagner ***@***.***>; Mention ***@***.***> Subject: Re: [microsoft/PowerPlatformConnectors] Added UiPath PA Connector (PR #1311) Hi @GitRob77<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGitRob77&data=04%7C01%7Crobert.wagner%40uipath.com%7Ca5a6748492664738b6bd08d9b9bb11ab%7Cd8353d2ab1534d178827902c51f72357%7C0%7C0%7C637745035378295842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aR6yvhOB1hLGcjudElsxqS2NfNUZl%2FWZHRu%2BzzJFoEs%3D&reserved=0> thanks for your submission! We just want to confirm whether this is an Independent Publisher connector or not, especially since the Publisher is listed as UIPath. Do you work at UIPath? If not, this would be an Independent Publisher connector and the Publisher should be you and your colleague's name, while the StackOwner would be UIPath. Also, I noticed that you wrote this would be private preview of the connector. Do you mind providing more context? - You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FPowerPlatformConnectors%2Fpull%2F1311%23issuecomment-988220420&data=04%7C01%7Crobert.wagner%40uipath.com%7Ca5a6748492664738b6bd08d9b9bb11ab%7Cd8353d2ab1534d178827902c51f72357%7C0%7C0%7C637745035378305834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=F9KomOxjsZU9nsxuRkEVEl27CU08nVPuoHCHj4RnXRU%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASOMYYIT5AHZYRPQX5P5NALUPZQW3ANCNFSM5JRXYOOQ&data=04%7C01%7Crobert.wagner%40uipath.com%7Ca5a6748492664738b6bd08d9b9bb11ab%7Cd8353d2ab1534d178827902c51f72357%7C0%7C0%7C637745035378305834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u8ViMr1KlbwYq60AvbgdiWUFJIu36G44L2KWNGq3hMw%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crobert.wagner%40uipath.com%7Ca5a6748492664738b6bd08d9b9bb11ab%7Cd8353d2ab1534d178827902c51f72357%7C0%7C0%7C637745035378315836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CPPU4Hlg2ShT5%2FKn7yPsrPSFMlggXyFZu2EbEoT2tjI%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crobert.wagner%40uipath.com%7Ca5a6748492664738b6bd08d9b9bb11ab%7Cd8353d2ab1534d178827902c51f72357%7C0%7C0%7C637745035378315836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4etHUMQMRFbTv1S2fhOugnyRFEOJJQFcAbcLfTDkar4%3D&reserved=0>.

Hi @GitRob77, Apologies for the delay in getting back to you. We had a few deployment and certification freezes in the last month and have a higher volume of submissions. If you want to deploy the connector as a private preview connector - It is not allowed to deploy any custom connector to our production region for beta testing. But I have a few suggestions which can help you in this scenario. Can you please start an email thread with us (ConnectorPartnerMgmtTeam@service.microsoft.com) by elaborating your requirement, We will assist you with the best possible solutions at the earliest. Thanks.

**Review by taylor-hazlett — APPROVED** [review]

**Review by taylor-hazlett — APPROVED** [review]

**Comment by mamurshe** [comment]
@TuckermanRav I presumed that the merge was inadvertent. I will sync with @taylor-hazlett  and undo my revert if I made a mistake.

**Comment by GitRob77** [comment]
> 

@mamurshe No custom connector deployment please.
We had this idea initially when we thought we could do a quick testing before we launch it. 
We dropped this idea a while ago.

Please deploy this as Certified Standard Connector.

Thank you for all your efforts!

**Comment by Amjed-Ayoub** [comment]
Hi @GitRob77 and @TuckermanRav, thank you for your interest in publishing your connector. Publishing Custom Connectors is NOT allowed. if you would like to publish this connector, please resubmit your pull request as a certified connector.
Please let us know if you have any questions.
Thank you again for working with us.

**Comment by Amjed-Ayoub** [comment]
Hello Everyone,
I hope you are doing well.
I am following up with you on my message above. 
Please let me know if you have any questions.

**Pull request merged**
