### PR TITLE
OpenAI (Addition of Whisper API to Robin Rosengrün's connector) (Independent Publisher)

### PR DESCRIPTION
**Pull request by PriyaranjanKS**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

# Proposal - <Whisper Open AI> (Independent Publisher)

This is an addition to the Open AI connector by Robin Rosengrun . The proposed additional endpoint leverages the Whisper Open AI to perform robust audio processing, providing functionalities for transcribing and translating audio to text.

### Transcribe Audio

This action allows the transcription of audio into text, providing a convenient method to convert spoken words within an audio file into written text for various applications.

### Translate Audio

This action allows the translation of audio from any language to english language text

# Implementations

Screenshots of the implementation are as below : 

## Actions without Parameters
InputWithoutParameters

## Actions with Parameters
InputWithParameters

## Output in Power Automate Designer
Output

## Output in Customer Connector Creation Phase
Since the Test window do not allow file uploading, sharing the output from Swagger test section 
CustomConnectorTest

### CODE REVIEW

**Comment by PriyaranjanKS** [comment]
@vmanoharas  Requesting your review for proceeding with the addition of the connector

**Review by vmanoharas — COMMENTED** [review]
Hello @PriyaranjanKS, 

Thank you for submitting proposal, please refer below link and proceed with submitting all the files. 

https://github.com/microsoft/PowerPlatformConnectors/tree/dev/templates/Independent%20Publisher

**Review by PriyaranjanKS — COMMENTED** [review]
Updated the files with the new endpoints and details

**Comment by PriyaranjanKS** [comment]
> Hello @PriyaranjanKS,
> 
> Thank you for submitting proposal, please refer below link and proceed with submitting all the files.
> 
> https://github.com/microsoft/PowerPlatformConnectors/tree/dev/templates/Independent%20Publisher

@vmanoharas I have updated the existing connector files after validating the changes using paconn and ensuring that there are no breaking changes to existing functionalities. Please let me know if there is something additional I can do from my end. 

While editing the swagger files, I did not find an option to list myself as a publisher along with Robin in the connection creation section. Though I have updated the api properties with publisher details, it is not getting reflected in the Connection Creation page. Request your help with the same.

**Comment by PriyaranjanKS** [comment]
> @PriyaranjanKS please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by vmanoharas** [comment]
> > Hello @PriyaranjanKS,
> > Thank you for submitting proposal, please refer below link and proceed with submitting all the files.
> > https://github.com/microsoft/PowerPlatformConnectors/tree/dev/templates/Independent%20Publisher
> 
> @vmanoharas I have updated the existing connector files after validating the changes using paconn and ensuring that there are no breaking changes to existing functionalities. Please let me know if there is something additional I can do from my end.
> 
> While editing the swagger files, I did not find an option to list myself as a publisher along with Robin in the connection creation section. Though I have updated the api properties with publisher details, it is not getting reflected in the Connection Creation page. Request your help with the same.

Hi @PriyaranjanKS 

There is no publisher option in swagger file, we have contact information.  Publisher is available only in api properties file.

**Comment by vmanoharas** [comment]
Hello @PriyaranjanKS, 

Could you kindly verify the process by which you acquired this connector from Robin Rosengrün? Has this information been communicated to Robin Rosengrün and received their approval? Please confirm.

CC: robin@r2power.de

**Comment by PriyaranjanKS** [comment]
> Hello @PriyaranjanKS,
> 
> Could you kindly verify the process by which you acquired this connector from Robin Rosengrün? Has this information been communicated to Robin Rosengrün and received their approval? Please confirm.
> 
> CC: [robin@r2power.de](mailto:robin@r2power.de)

Hello @vmano

> Hello @PriyaranjanKS,
> 
> Could you kindly verify the process by which you acquired this connector from Robin Rosengrün? Has this information been communicated to Robin Rosengrün and received their approval? Please confirm.
> 
> CC: [robin@r2power.de](mailto:robin@r2power.de)

Hello @vmanoharas , Since this was my first attempt at submitting updates to an existing connector, was not sure about the process of getting approvals from the original publisher. I have taken the existing swagger files and updated the additional end point details. Would love Robin to review and provide approval/rejection comments for the same.

**Comment by PriyaranjanKS** [comment]
@vmanoharas Hello , just checking to see if there is something we can do to expedite the merge as we dont see a momentum for past 3 weeks

**Comment by vmanoharas** [comment]
Hello @robin@r2power.de, 

Could you please review provide your approval to proceed futher?

**Comment by vmanoharas** [comment]
Hello @PriyaranjanKS, kindly contact [robin@r2power.de](mailto:robin@r2power.de) through email and take an action soon, as this PR is in open state from many months.

**Comment by PriyaranjanKS** [comment]
> Hello @PriyaranjanKS, kindly contact [robin@r2power.de](mailto:robin@r2power.de) through email and take an action soon, as this PR is in open state from many months.

@vmanoharas Considering that there is already another endpoint with this functionality in the connector ecosystem , closing this PR

**Comment by vmanoharas** [comment]
> > Hello @PriyaranjanKS, kindly contact [robin@r2power.de](mailto:robin@r2power.de) through email and take an action soon, as this PR is in open state from many months.
> 
> @vmanoharas Considering that there is already another endpoint with this functionality in the connector ecosystem , closing this PR

Thank you @PriyaranjanKS

**Pull request closed without merging**
