### PR TITLE
Updated swagger definition due to API changes

### PR DESCRIPTION
**Pull request by mtcantero**
Modified capital from integer to number

### CODE REVIEW

**Review by sriyen-msft — CHANGES_REQUESTED** [review]
@mtcantero Breaking Changes: PFA log, It appears that you are updating some aspects of your connector update that will introduce breaking changes to your users. Could you please confirm that there will be no external users affected for this connector.

`The type has been changed for the output field. Existing flows may be broken if they are using this field and actual payload has been changed. ValuePath: operation/Libreborme-company_by_slug/responses/200/schema/company/capital/type Source: NewSwagger`

`The type has been changed for the output field. Existing flows may be broken if they are using this field and actual payload has been changed. ValuePath: operation/Libreborme-company_by_nif/responses/200/schema/company/capital/type Source: NewSwagger`

**Comment by mtcantero** [comment]
Hi @sriyen-msft  exactly we had to change the type of the output field "capital" from integer to number as there was an update yesterday on the API. The capital value has been changed to Float by the owner of the service and we got notified yesterday afternoon. The reasoning for that is because they were rounding up the capital value and after some feedback from the users of the API the owner of the service is no longer rounding up the value but leaving it as a float.

If a Power Automate user tries to retrieve company information that contain the capital they will receive an error message like this one:
image

The change that we did was modifying the type expected in the API definition to be number rather than integer so it doesn' t break when receiving a float value from the service.

Screenshot of updated custom connector:
image

Screesshot of the output showing a float value on the capital field:
image

Any other question please let us know.

Thank you for your help!

**Comment by sriyen-msft** [comment]
@mtcantero Update - We are preparing your connector for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes between 7-10 business days. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps. Thanks

**Comment by sriyen-msft** [comment]
[[certify-connector]]

**Comment by sriyen-msft** [comment]
@mtcantero Deployment freeze notice: Due to Thanksgiving week in the United States, we have temporarily halted the deployments of all the connectors till Tuesday, 30th November 2021. So we will not be able to deploy your connector to the next production region.

We will begin the deployments on Wednesday, 1st December 2021, and the production deployment of your connector in all regions will be expected to be completed by Thursday, 2nd December 2021. Thanks

**Comment by mtcantero** [comment]
Thanks @sriyen-msft ! Have a fantastic Thanksgiving weekend and talk to you on December 1st!

**Comment by sriyen-msft** [comment]
@mtcantero Congratulations! The deployment of your connector and documentation page is now complete, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program. Thanks

**Review by sriyen-msft — APPROVED** [review]

**Pull request merged**
