### PR TITLE
Initial Version of the Survalyzer Connector

### PR DESCRIPTION
**Pull request by BenjaminLutz80**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by BenjaminLutz80** [comment]
@microsoft-github-policy-service agree [company="Survalyzer AG"]

**Comment by BenjaminLutz80** [comment]
@microsoft-github-policy-service agree company="Survalyzer AG"

**Comment by BenjaminLutz80** [comment]
> Hi Benjamin, Have you looked into configuring an additional connection parameter for the host and then setting it using the Set Host policy? This doesn’t work with OAuth, but I think your OAuth isn’t by host. https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/expressions/expressions
> 
> CC: @Amjed-Ayoub

The two data centers are completely isolated also in terms of OAuth. We have indeed two different identity servers. So I guess splitting the connectors is at least for the time being the only way.

**Comment by Amjed-Ayoub** [comment]
@BenjaminLutz80 You can set a dynamic host URL, please to take a look at https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/dynamichosturl/dynamichosturl. 
Let me know if you have any questions.

**Comment by BenjaminLutz80** [comment]
> @BenjaminLutz80 You can set a dynamic host URL, please take a look at https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/dynamichosturl/dynamichosturl.
> 
> Please allow me to share [this example](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/certified-connectors/SmartCOMM%20Doc-Gen/apiProperties.json#:~:text=%7D%2C-,%22policyTemplateInstances%22%3A%20%5B,%7D,-%5D%2C) with you as well. Please let me know if you have any questions.

This approach doesn't work with apiDefinition.swagger.json because there I can't pass the check if I provide any variable. You can see my attempts in my previous checkins and all failed. I'm happy to change the connectors and parametrize them but it needs to works for all parts means for the 3 OAuth host and for the OpenId host since all of them are individual for each data center. If there is a way please provide an example how I can achieve it comprehensively.

**Comment by Amjed-Ayoub** [comment]
@BenjaminLutz80 we can proceed with multiple connector :-). May I ask you please to submit each connector in a separate PR. this will make it easier to make the ISV Studio submission using the commit ID for each connector. 
Please let me know if you have any questions.

**Comment by BenjaminLutz80** [comment]
> @BenjaminLutz80 we can proceed with multiple connector :-). May I ask you please to submit each connector in a separate PR. this will make it easier to make the ISV Studio submission using the commit ID for each connector. Please let me know if you have any questions.

I removed the Swiss version and create a separate PR for it as requested.

**Comment by Amjed-Ayoub** [comment]
@BenjaminLutz80 thank you so much for removing the other connector form this PR. 
Unfortunately, it looks like your branch is not up to date. You are changing other connectors files :-).
image

Please update the branch and update this PR. feel free to close this one and create a new one if easier.
image


I don't see the second connector pull request.
Please make sure to have a private branch for each connector and submit 2 PRs, one for each branch.

Please let me know if you have any questions.

**Pull request closed without merging**
