### PR TITLE
IPQualityScore Open Source Review (Version 2.0)

### PR DESCRIPTION
**Pull request by RamboV**
---
When submitting a connector, please check the following conditions for your PR to ensure a smooth certification process.

- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Review by sriyen-msft — CHANGES_REQUESTED** [review]
@RamboV There are few differences b/w the swagger you have uploaded in the ISVStudio and this PR. Can you please make sure that you have provided updated artifacts in the PR

**Review by sriyen-msft — CHANGES_REQUESTED** [review]
@RamboV Please resolve the branch conflicts to get the PR approved and merged

**Comment by sriyen-msft** [comment]
@RamboV Noticed that you have submitted us an update, Can you please let me know if this PR has latest artifacts which you have uploaded for v2.0 ?

**Comment by RamboV** [comment]
> @RamboV Noticed that you have submitted us an update, Can you please let me know if this PR has latest artifacts which you have uploaded for v2.0 ?

HI @sriyen-msft , Yes this PR contains all the latest artifacts for v2.0

**Comment by sriyen-msft** [comment]
> > @RamboV Noticed that you have submitted us an update, Can you please let me know if this PR has latest artifacts which you have uploaded for v2.0 ?
> 
> HI @sriyen-msft , Yes this PR contains all the latest artifacts for v2.0

Thank you so much for your reply, So please resolve the branch conflicts to get this PR and merged.

**Comment by RamboV** [comment]
> > > @RamboV Noticed that you have submitted us an update, Can you please let me know if this PR has latest artifacts which you have uploaded for v2.0 ?
> > 
> > 
> > HI @sriyen-msft , Yes this PR contains all the latest artifacts for v2.0
> 
> Thank you so much for your reply, So please resolve the branch conflicts to get this PR and merged.

Hi @sriyen-msft ,
I have resolved the branch conflicts. Thanks.

**Review by sriyen-msft — APPROVED** [review]

**Pull request merged**
