### PR TITLE
Axtension/connector

### PR DESCRIPTION
**Pull request by JoepKillaars**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### CODE REVIEW

**Comment by sriyen-msft** [comment]
@JoepKillaars Can you please sign the CLA license, mentioned in the PR

**Comment by JoepKillaars** [comment]
> @JoepKillaars , Can you please let us know why you have updated remaining 118 files of other certified connectors ? **Please remove changes of other connector from this PR.**

I did not change anything from other connectors. As you can see the commits made by me are just on our own files. If you compare to [master], the only thing changed are our own files. This PR tries to merge into :dev branch, which, as you mentioned, contains other changes not yet in master. 

Please suggest how to resolve this. The changes are NOT in my branch and I cannot remove them.

**Comment by sriyen-msft** [comment]
@JoepKillaars Please close this PR as you have raised a new PR with required files, Thanks

**Comment by JoepKillaars** [comment]
Closing this PR because another one is being processed.

**Pull request closed without merging**
