### PR TITLE
Removed Michael Scott Quotes connector as the underlying heroku app i…

### PR DESCRIPTION
**Pull request by Ryanb58**
This connector does not work. I tested it in preprod and it failed with a 404 returned. Looked at the host parameter in this app, it no longer exists. Cleaning up as this is dead configuration+connector.

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by vmanoharas** [comment]
Hello @Ryanb58, 

Unfortunately, we cannot delete the connector, kindly deprecate and connector and submit it. Please close this PR. 

Please see the deprecate process documentation - https://learn.microsoft.com/en-us/connectors/custom-connectors/deprecate-operation

**Comment by vmanoharas** [comment]
> Hello @Ryanb58,
> 
> Unfortunately, we cannot delete the connector, kindly deprecate and connector and submit it. Please close this PR.
> 
> Please see the deprecate process documentation - https://learn.microsoft.com/en-us/connectors/custom-connectors/deprecate-operation

Hello @Ryanb58, I am following up on my previous comment, kindly address the same.

**Comment by Ryanb58** [comment]
@vmanoharas Why can this connector not be removed? The underlying service it connects to is defunct. Any flow using it would not be working if they still consume or use this.

**Comment by vmanoharas** [comment]
Hello @Ryanb58, 

Unfortunately, we don’t allow deleting a connector as it will break all existing flows(where the connector’s actions are being used) for Power Automate users. 

Please deprecate your connector https://learn.microsoft.com/en-us/connectors/custom-connectors/deprecate-operation

**Comment by troystaylor** [comment]
This is my connector and I will deprecate those actions.

**Comment by vmanoharas** [comment]
Thank you @troystaylor, Can this PR closed by @Ryanb58? if yes, I would recommend @Ryanb58 to close this PR.

**Comment by troystaylor** [comment]
Yes, @Ryanb58 please close this PR.

**Pull request closed without merging**
