### PR TITLE
Sapling.ai (Independent Publisher)

### PR DESCRIPTION
**Pull request by fordosa90**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by Amjed-Ayoub** [comment]
Hello @fordosa90,

Thank you so much for submitting this new proposal. We are looking forward to seeing your connector artifacts.

Please let us know if you have any questions.

Thank you so much again for your hard work with us.

**Comment by fordosa90** [comment]
@Amjed-Ayoub Thank you, actually I have a question, as I have started to work on the connector.
I was able to map most of the endpoints, requests and responses of the service to the custom connector.
However, this API requires the API key to be sent within every request (POST) to the endpoint within the request JSON body, for example:

HTTP POST
....../api/v1/testendpoint
{
  "key": <API_KEY>,
  "text": "This is a test text",
  "sesions_id": 12345
}

I am unable to find any way on how to define this authentication type except making the API Key itself an input parameter available through the user interface. Do you have any suggestions?

**Comment by fordosa90** [comment]
@Amjed-Ayoub the only workaround that comes to my mind is adding "Authentication: API Key" to the connector, and the adding a request parameter to every paths (endpoints) defaulting to this, and marking it as "internal".

**Comment by troystaylor** [comment]
Hi Andras,
I have seen this authentication method before. In the past, I used no security method and created the connection parameter manually after downloading it with the CLI. The problem I couldn't get past was then using the policy Set Property (https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/setproperty/setproperty) to add the connection parameter, as the policy couldn't at the time reference the connection parameter. I would try this and let us know if it works. You would then not need to set the parameter as internal as it wouldn't be shown to the user as part of the action.

**Comment by Amjed-Ayoub** [comment]
Thank you so much @fordosa90 for reaching out and thank you @troystaylor for your help. Please allow me to add this document (https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/setqueryparameter/setqueryparameter) as well.

**Comment by fordosa90** [comment]
@troystaylor  @Amjed-Ayoub 
Thank you for the input and suggestions.
I have tried to Set-Property (preview) policy with using the @connectionParameter('...') notation, which does add correctly the property to the HTTP POST body, however does not resolve the connectionParameter to an actual value...
Might be this a bug, or rather the fact that since it is a preview feature, it does not yet support this expression?

Is the above mentioned workaround (defaulting value to connection param, and hiding it as internal) a not suggested solution?

image


While this arrives to my testing endpoint as follows:
image

**Comment by troystaylor** [comment]
> 

Can you add your apiProperties.json file to the PR so I can check that out? That is where the api_key property needs to be added to give the user the input box.

**Comment by fordosa90** [comment]
@troystaylor  sure, updated PR with the file
thanks a lot for the check and any assist

**Comment by troystaylor** [comment]
> @troystaylor sure, updated PR with the file thanks a lot for the check and any assist

Try giving the parameter a different name. The more I think about it, the more I think that api_key is a reserved name. The policy looks configured correctly.

**Comment by fordosa90** [comment]
hey @troystaylor  thank you for the quick feedback.
I have actually tried that with both 'key' and 'er', and none of them works.
Both of them sent through the expression without resolving it first.

**Comment by troystaylor** [comment]
I'm at a bit of a loss. I've created my own version using the Postman collection (https://app.getpostman.com/run-collection/20248607-4e2eafd4-e941-4d52-88a8-b4bb90c1d26a?action=collection%2Ffork&collection-url=entityId%3D20248607-4e2eafd4-e941-4d52-88a8-b4bb90c1d26a%26entityType%3Dcollection%26workspaceId%3Dcea8d224-5c5e-4604-a8f6-46f228f46f78), downloaded it to add the connectionParameter, then uploaded it, refreshed the connector, added the policy, and tested - didn't get the key. I then went to the policy and added the API key as the value instead of connectionParameters('key') - worked. @jopanchal, can you have someone look at the Set Property policy code?

**Comment by Amjed-Ayoub** [comment]
@fordosa90 if this connector is ready for review, please remove the proposal from the PR title.

**Comment by fordosa90** [comment]
@Amjed-Ayoub no, the connector is not yet ready as the question of authentication is still open.
Waiting for input from Microsoft team at the moment

**Comment by vmanoharas** [comment]
Hello @fordosa90, 

if this connector is ready for review, please remove the proposal from the PR title. As I have seen that @troystaylor has given workaround. https://github.com/microsoft/PowerPlatformConnectors/issues/2906

**Comment by fordosa90** [comment]
@vmanoharas  the connector is still in proposal, I would prefer to receive an official answer from MSFT before utilising any workaround instead of the supported and suggested solution

@troystaylor  greatly appreciate the additional effort you have invested into this issue

**Comment by fordosa90** [comment]
@vmanoharas  I can finally confirm, that the connector is ready for merge 🥳 
Based on feedback from product team, the policy template can not be used with the expressions, this is marked in a fairly hidden way on each policy templates first paragraph.

Implemented an alternative workaround with the help of small code, since there is no supported native way (hidden input properties can't reference directly connection parameters either),

**Comment by fordosa90** [comment]
image

**Comment by vmanoharas** [comment]
Hello @fordosa90, Thank you very much for submitting the PR finally :-). 

The validation checkers are failing, could you please close this PR and resubmit with new PR?

**Pull request closed without merging**
