### PR TITLE
Proposal - Tophhie Cloud (Independent Publisher)

### PR DESCRIPTION
**Pull request by Tophhie**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

{35E97B44-FA7D-424A-B465-F3374DF59C46}
{FA702902-1DDC-4ACE-8E54-160AD19363BF}

### CODE REVIEW

**Comment by troystaylor** [comment]
Hi @Tophhie, looking forward to seeing what this connector can do. Please let me know if I can be of any assistance getting your connector built.
Please note, as I notice the name of the connector and your Github handle are the same, the requirements for an Independent Publisher vs. a verified publisher: https://learn.microsoft.com/en-us/connectors/custom-connectors/submit-certification#who-is-eligible-to-get-a-connector-and-plugin-certified

**Comment by Tophhie** [comment]
@microsoft-github-policy-service agree

**Comment by vmanoharas** [comment]
Hello @Tophhie, 

Could you please respond to @troystaylor message above before proceeding for the review?

**Comment by Tophhie** [comment]
@vmanoharas & @troystaylor, I've closed the pull request for now, just whilst I investigate the Verified Publisher route. I'm already registered in Microsoft Partner Network, so this might be the route we go down.

**Pull request closed without merging**
