### PR TITLE
Second submission of TPS & CTPS Checker connector

### PR DESCRIPTION
**Pull request by WilkoUK**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

@microsoft-github-policy-service agree company="Wilkins Computing Services Limited"

### CODE REVIEW

**Comment by WilkoUK** [comment]
@microsoft-github-policy-service agree [company=“Wilkins Computing Services Limited"]

**Comment by vmanoharas** [comment]
Thank you very much for creating new PR. However, as mentioned in my previous PR, kindly don't merge the PR until we approve the PR, but this PR merged as well. 

Additionally, kindly accept the lca, this is not agreed yet. 

image

**Comment by WilkoUK** [comment]
Good Morning. 
I have replied to the ICA, is there something else I need to do?

Do you require me to close the PR and delete the clone repository and start over?

Kindest Regards,
Paul

**Comment by vmanoharas** [comment]
Good morning @WilkoUK, 

Thank you very much for your response. Unfortunately, you have not agreed the CLA yet. Yes please close this PR and reopen the PR and kindly don't merge the PR until the PR is approved. 

image

**Comment by WilkoUK** [comment]
Good Morning & Happy Monday.


Due to all of the problems, I have deleted everything and started over. You should find a new PR. I have not touched the repo in any other way. 
Over to you.


Paul Wilkins

***@***.***

**Pull request closed without merging**
