### PR TITLE
Update apiDefinition.swagger.json

### PR DESCRIPTION
**Pull request by calvinleong**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### CODE REVIEW

**Comment by mamurshe** [comment]
@calvinleong Please update your fork from upstream: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
Please fix the conflict and resubmit.

**Comment by calvinleong** [comment]
> @calvinleong Please update your fork from upstream: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
> Please fix the conflict and resubmit.

Can you please help me complete this task? I am not sure on the exact steps I need to take?

**Comment by sriyen-msft** [comment]
@calvinleong Please resolve the conflicts in the PR and Merge it.

**Comment by calvinleong** [comment]
> @calvinleong Please resolve the conflicts in the PR and Merge it.

The Merge pull request button is grayed out for me. There is a message that says "You're not authorized to merge this pull request". How do I get authorized to Merge the pull request?

**Comment by mamurshe** [comment]
Hi @calvinleong,
Can you please follow the documentation @dougelliott provided earlier to resolve the conflicts? Please let me know if you need help. Here is the [link to the doc](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).

**Comment by calvinleong** [comment]
> Hi @calvinleong,
> Can you please follow the documentation @dougelliott provided earlier to resolve the conflicts? Please let me know if you need help. Here is the [link to the doc](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).

Hello, Is it possible to schedule a Teams call to help walk me through this process?

**Comment by dougelliott** [comment]
> > Hi @calvinleong,
> > Can you please follow the documentation @dougelliott provided earlier to resolve the conflicts? Please let me know if you need help. Here is the [link to the doc](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).
> 
> Hello, Is it possible to schedule a Teams call to help walk me through this process?

@calvinleong I will send you an email and we'll work on getting things sorted out with you

**Comment by calvinleong** [comment]
@dougelliott I have updated the pull request.

**Comment by dougelliott** [comment]
@calvinleong Great, glad to see that was able to get resolved! All looks well with the conflicts now, but it looks like the `readme.md` has its contents duplicated in the file. When de-duped the actual content looks fine though.

**Comment by mmurshed** [comment]
> @calvinleong You'll need to do all the steps in the documentation provided [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) to ensure that the fork is synced with the upstream repo. Proper syncing of the fork should allow it to be merged later.
> 
> It also looks like your commit is for `connectors/gofileroom`, which doesn't exist. Instead, that path needs to be changed to `certified-connectors/gofileroom`. Apologies for missing this earlier.

@dougelliott Can you please approve the changes?

**Comment by dougelliott** [comment]
@mmurshed Still pending final changes from Calvin on the readme, then can be approved

@calvinleong Checking in on the the duplication that occurred in the readme. Can that be addressed to unblock the completion of the PR?

**Comment by sriyen-msft** [comment]
@calvinleong Please upload the updated apiProperties.json file in the PR as the policyTemplateInstance property is missing.

**Comment by sriyen-msft** [comment]
Followed up with the partner in certification portal to address the comments mentioned in the PR.

**Comment by mamurshe** [comment]
@sriyen-msft Please take a look.

**Comment by calvinleong** [comment]
> @calvinleong The apiProperties.json file looks outdated, can you please upload it, thanks

**Comment by calvinleong** [comment]
> > @calvinleong The apiProperties.json file looks outdated, can you please upload it, thanks

@sriyen-msft The apiProperties.json is unchanged. The uploaded version is up to date for me.

**Pull request closed without merging**
