### PR TITLE
Connect2all icon update

### PR DESCRIPTION
**Pull request by Joerio**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### CODE REVIEW

**Comment by dougelliott** [comment]
@Joerio Would you be able to fork off of master and recreate the PR for the commit to go into master as well? Thanks in advance.

**Comment by sriyen-msft** [comment]
Followed up with the partner in certification portal to address the comments mentioned in the PR

**Comment by Joerio** [comment]
@dougelliott I created a new pull request for master (#333 )
@sriyen-msft I could change that, but it should be gaccloud. The azurewebsites url is a dev url and not the production url. The currently deployed connector is also communicating with gaccloud and not with azurewebsites.

**Comment by dougelliott** [comment]
@Joerio We went ahead and approved the other PR. Could this one be closed out as a result?

**Pull request closed without merging**
