### PR TITLE
Seismic Workspace (Verified Publisher)

### PR DESCRIPTION
**Pull request by amit-chaudhari1**
This PR update is according some new endpoints within the seismic API.
Please Review and Merge.
Thankyou,

### CODE REVIEW

**Comment by amit-chaudhari1** [comment]
@Amjed-Ayoub Can you please provide me with some context to why this is failing, I am not authorized to look at the logs for "Swagger and Change validation" 
image

There's some changes in the URL's within our API which meant that we had to change the base URL of this connector, we meant to do that change.

**Comment by amit-chaudhari1** [comment]
@vmanoharas  Can you please take a look at why this fails ?

The error shown is not clear, ` PowerShell exited with code '1'. `

**Comment by vmanoharas** [comment]
Hi @amit-chaudhari1, 
We have encountered a validation issue, and our team is actively working to resolve it as quickly as possible.

**Comment by rkushvaha** [comment]
Hi @vmanoharas any updates on this?

**Comment by vmanoharas** [comment]
Hi @amit-chaudhari1 
Apologies for the delay in resolving the issue; our engineering team is actively addressing it. We appreciate your patience, and we're committed to fixing the problem within a week. Thank you for understanding.

**Comment by amit-chaudhari1** [comment]
@vmanoharas I hope you folks will let us know when you resolve this.

**Comment by rkushvaha** [comment]
@vmanoharas Any updates on this?

**Comment by vmanoharas** [comment]
Hello @rkushvaha, 

The pipeline was experiencing internal issues, we have resolved them. Could you please resubmit your PR/commit so that it can be triggered again and undergo validation? Thank you for your understanding. We apologize any inconvenience caused.

**Pull request closed without merging**
