### PR TITLE
Feb15test2

### PR DESCRIPTION
**Pull request by ZohoSign-integ**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by Amjed-Ayoub** [comment]
@ZohoSign-integ Thank you for your submission. Our Engineer will review your request.

**Comment by ZohoSign-integ** [comment]
@Amjed-Ayoub Just remainder on this to review this PR.

**Comment by Amjed-Ayoub** [comment]
@ZohoSign-integ thank you for the reminder and apologies for the delay in process. @sriyen-msft will review your request soon. Thank you for your patience.

**Comment by sriyen-msft** [comment]
@ZohoSign-integ Are you sure you are updating your connector? I can not see any file in the PR.

**Comment by ZohoSign-integ** [comment]
Have done necessary changes in the PR https://github.com/microsoft/PowerPlatformConnectors/pull/1464 . Please check.

**Comment by ZohoSign-integ** [comment]
@sriyen-msft Have made necessary changes in the PR https://github.com/microsoft/PowerPlatformConnectors/pull/1464 . Please check it.

**Comment by sriyen-msft** [comment]
@ZohoSign-integ, I am closing this PR as the updated files are uploaded in another PR.

**Pull request closed without merging**
