### PR TITLE
IN D Insurance (ICD10/CPT)

### PR DESCRIPTION
**Pull request by gayathri35**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Review by mamurshe — CHANGES_REQUESTED** [review]
Please remove apiProperties.json from the root folder

**Comment by sriyen-msft** [comment]
@gayathri35 

1) Please read all the [contributing instructions](https://github.com/microsoft/PowerPlatformConnectors#contributing) before open sourcing your connector's update.
2) Please sign CLA to get the PR reviewed and approved to merge.
3) Please remove the folder called `IN-D Insurance (ICD10 & CPT)` from `certified-connectors` folder. It is a duplicate folder created by you or your team.
4) Have your connector files in only `IN-D Insurance` folder.
5) You have uploaded unnecessary files, i.e. `apiProperties.json`, `apiDefinition.swagger.Insurance.json` and `apiDefinition.swagger.updated.Insurance.json`, Please remove these files
6) Upload only the required files, i.e.  `apiDefinition.swagger.json`, `apiProperties.json` and `readme.md`. No other file is required and not allowed.

**Review by sriyen-msft — CHANGES_REQUESTED** [review]
@gayathri35

Please read all the contributing instructions before open sourcing your connector's update.
Please sign CLA to get the PR reviewed and approved to merge.
Please remove the folder called IN-D Insurance (ICD10 & CPT) from certified-connectors folder. It is a duplicate folder created by you or your team.
Have your connector files in only IN-D Insurance folder.
You have uploaded unnecessary files, i.e. apiProperties.json, apiDefinition.swagger.Insurance.json and apiDefinition.swagger.updated.Insurance.json, Please remove these files
Upload only the required files, i.e. apiDefinition.swagger.json, apiProperties.json and readme.md. No other file is required and not allowed.

**Comment by sriyen-msft** [comment]
> @gayathri35
> 
> 1. Please read all the [contributing instructions](https://github.com/microsoft/PowerPlatformConnectors#contributing) before open sourcing your connector's update.
> 2. Please sign CLA to get the PR reviewed and approved to merge.
> 3. Please remove the folder called `IN-D Insurance (ICD10 & CPT)` from `certified-connectors` folder. It is a duplicate folder created by you or your team.
> 4. Have your connector files in only `IN-D Insurance` folder.
> 5. You have uploaded unnecessary files, i.e. `apiProperties.json`, `apiDefinition.swagger.Insurance.json` and `apiDefinition.swagger.updated.Insurance.json`, Please remove these files
> 6. Upload only the required files, i.e.  `apiDefinition.swagger.json`, `apiProperties.json` and `readme.md`. No other file is required and not allowed.

@gayathri35 Please let me know if the above instructions are not clear to you. I will try to elaborate in more in detail.

**Comment by sriyen-msft** [comment]
@gayathri35 Closing this PR as you are addressing the issues in the new PR.

**Pull request closed without merging**
