### PR TITLE
e-sign custom connector

### PR DESCRIPTION
**Pull request by eSignHQ**
---
Please check the following conditions for your PR.

- [ ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Comment by dougelliott** [comment]
@eSignHQ Could the files please be placed within the `certified-connectors` directory, rather than the `custom-connectors directory`? Thanks!

**Comment by eSignHQ** [comment]
@dougelliott done now.

**Comment by sriyen-msft** [comment]
@eSignHQ Please remove icon from the PR

**Comment by eSignHQ** [comment]
Why can’t you @microsoft just feed us back a list of corrections in one go, instead of asking for one individual fix from us every 24 hours?!

**Comment by eSignHQ** [comment]
There is no logo in the PR?

**Comment by eSignHQ** [comment]
Is this OK?

**Comment by dougelliott** [comment]
@eSignHQ This looks good, I will go ahead and approve :)

**Review by dougelliott — APPROVED** [review]

**Pull request merged**
