### PR TITLE
WooCommerce

### PR DESCRIPTION
**Pull request by nhance**
WooCommerce is a free, open-source commerce platform for WordPress. It empowers anyone, anywhere, to sell anything – with unlimited extensibility, flexibility, and control.

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`.

### CODE REVIEW

**Comment by Amjed-Ayoub** [comment]
@nhance thank you for your submission. Our Engineer will review your request.

**Comment by Amjed-Ayoub** [comment]
Dear partner,

We apologize for the delay you might be experiencing while we are working on a high volume of connector requests. Rest assured that we are doing everything we can to address this volume. We are taking measures like improving our processes and hiring additional team members to guarantee resolving your connector requests in a timely manner. 

Please let us know if you have any questions in the meantime.

**Comment by nhance** [comment]
Pull request is open but it looks like we may need some changes to proceed. Leaving the PR open to reserve this connector as we are working through release process with the stack owner.

**Comment by Amjed-Ayoub** [comment]
Hello @nhance, Thank you for the update. Please let us know when you are ready to proceed forward with the PR.
We look forward to getting your connector certified.
Thank you very much.

**Comment by Amjed-Ayoub** [comment]
Hi @nhance, I hope you are doing well. I am following up with you to see how things are going with your connector.
Please let me know if you have any questions.
Thank youvery much

**Comment by Amjed-Ayoub** [comment]
Hi @nhance, I hope you are doing well.
can you please share an ETA on when you think your connector files will be ready?
Please let me know if you have any questions.
Thank you very much.

**Comment by nhance** [comment]
Hi @Amjed-Ayoub we have this ready for review, but I want to bring to your attention the fact that the Webhook DELETE is failing in this connector. It appears that when using this the DELETE request comes over with a different authorization header.

**Comment by nhance** [comment]
Thanks @Amjed-Ayoub I did follow the steps in that link and had posted a reply to re-open that thread yesterday. I will take keep conversation in that thread on the Power Automate community page so we don't clog up the pull request.

**Comment by sriyen-msft** [comment]
@nhance I'm just checking in to see how things are going with updating your connector artifacts as per the given feedback. Please feel free to reach out with any questions you may have, Thanks.

**Comment by nhance** [comment]
@sriyen-msft This connector is ready for final review. Artifacts are updated as requested.

**Review by sriyen-msft — APPROVED** [review]

**Pull request merged**
