### PR TITLE
Encodian - Nov 23 Release

### PR DESCRIPTION
**Pull request by Encodian**
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

### CODE REVIEW

**Comment by vmanoharas** [comment]
Hello @Encodian, 

You have created this PR from the master branch, can you please create it from your fork repository?

**Comment by Encodian** [comment]
> Hello @Encodian,
> 
> You have created this PR from the master branch, can you please create it from your fork repository?

Hello @vmanoharas 

This PR was generated from Encodian:master which was forked from microsoft/PowerPlatformConnectors.... before we create a new release we perform a hard reset on Encodian:master from the upstream/dev branch... i.e. microsoft:dev 

Why do you think this was created from microsoft:master?

**Comment by vmanoharas** [comment]
> > Hello @Encodian,
> > You have created this PR from the master branch, can you please create it from your fork repository?
> 
> Hello @vmanoharas
> 
> This PR was generated from Encodian:master which was forked from microsoft/PowerPlatformConnectors.... before we create a new release we perform a hard reset on Encodian:master from the upstream/dev branch... i.e. microsoft:dev
> 
> Why do you think this was created from microsoft:master?

Hi @Encodian, 

Thank you for your quick turn around. 
There are couple of swagger validation errors, please check, but I could not find this in the current swagger file.

Can you please look into them and correct it if you find them in the json file? so that I will approve. 

The property is internal and has a default value, it must be required. Optional internal fields are ignored. ValuePath: /definitions/DtoCreateBarcode/**dotCodemask**

The property is internal and has a default value, it must be required. Optional internal fields are ignored. ValuePath: /definitions/DtoCreateBarcode/**dotCodemask**

**Comment by Encodian** [comment]
> > > Hello @Encodian,
> > > You have created this PR from the master branch, can you please create it from your fork repository?
> > 
> > 
> > Hello @vmanoharas
> > This PR was generated from Encodian:master which was forked from microsoft/PowerPlatformConnectors.... before we create a new release we perform a hard reset on Encodian:master from the upstream/dev branch... i.e. microsoft:dev
> > Why do you think this was created from microsoft:master?
> 
> Hi @Encodian,
> 
> Thank you for your quick turn around. There are couple of swagger validation errors, please check, but I could not find this in the current swagger file.
> 
> Can you please look into them and correct it if you find them in the json file? so that I will approve.
> 
> The property is internal and has a default value, it must be required. Optional internal fields are ignored. ValuePath: /definitions/DtoCreateBarcode/**dotCodemask**
> 
> The property is internal and has a default value, it must be required. Optional internal fields are ignored. ValuePath: /definitions/DtoCreateBarcode/**dotCodemask**

@vmanoharas - ok, we'll rebase and create a new PR... will be a lot simpler for you to merge then

**Pull request closed without merging**
