### PR TITLE
HYAS Insight Connector Submission for Review

### PR DESCRIPTION
**Pull request by RamboV**
---
Please check the following conditions for your PR.

- [x] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [x] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Comment by dougelliott** [comment]
@RamboV Could you please sign the CLA? Thanks in advance!

**Comment by RamboV** [comment]
@Doug Elliott (Artech Consulting LLC)<mailto:v-wiell@microsoft.com>  I have done it.

Regards,
Venkat Rambatla

________________________________

**Comment by dougelliott** [comment]
@RamboV Great, thanks! The `icon.png` and `settings.json` files should be removed from the PR, but once that's done I can go ahead and approve.

**Comment by RamboV** [comment]
@dougelliott, The icon.png, settings.json files have been removed from the PR.

Thanks.

**Review by dougelliott — APPROVED** [review]

**Comment by dougelliott** [comment]
@RamboV Thanks! Approving.

**Pull request merged**
