### PR TITLE
Seismic Workspace (Verified Publisher) 

### PR DESCRIPTION
**Pull request by amit-chaudhari1**
This PR update is according some new endpoints within the seismic API.
Please Review and Merge.
Thankyou,

### CODE REVIEW

**Comment by vmanoharas** [comment]
Hi @amit-chaudhari1 

As per the swagger validation check you have modified the path template. can you please confirm that no existing flows or users will be affected by this change?

**Review by vmanoharas — COMMENTED** [review]
Hi @amit-chaudhari1

As per the swagger validation check you have modified the path template. can you please confirm that no existing flows or users will be affected by this change?

**Comment by vmanoharas** [comment]
Hi @amit-chaudhari1, 

Could you please update us on above comments?

**Comment by amit-chaudhari1** [comment]
> As per the swagger validation check you have modified the path template. can you please confirm that no existing flows or users will be affected by this change?

Hi @vmanoharas , sorry for the late reply.
No, I don't think anyone will be affected. Please merge if everything looks okay.

**Comment by vmanoharas** [comment]
Hi @amit-chaudhari1, 

Thank you very much for the reply.

**Review by vmanoharas — APPROVED** [review]
Hello @amit-chaudhari1 
I hope you are doing well.
Congratulations, your pull request is approved and merged. Please [submit the files to ISV Studio](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) or [update your submission](https://learn.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#update-submission-prior-to-certification) using your latest commit ID, please allow us up to 1-2 weeks to review your submission, and our Engineers will notify you in the “Activity Control” area in ISV Studio. Please [make sure that the icon meets all the requirements](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-submission#design-an-icon-for-your-connector), that it’s size is 230x230, icon background is not white or transparent and it matches the iconBrandColor property in apiProperties.json file.
After making the submission in ISV Studio, please attach an intro.md file in the activity control section. This file is required and it's different from readme.md. You can [find an example of intro.md file on this page](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) at step 6.
Please [Create an environment in the Preview region](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#create-an-environment-in-the-preview-region). You will use this environment later to [test your connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#test-your-connector) after Microsoft is done with the functional verification for your connector.
We expect all tests to be completed within 1-2 weeks.
If your connector passes all tests, the deployment process begins, and it typically takes up to 3 to 4 weeks to deploy your connector to all of our regions.
Please let me know if you have any questions or run into any problems while creating or updating your submission.
Thank you very much for working with us.

**Pull request merged**
