### PR TITLE
iAuditor PA connector files

### PR DESCRIPTION
**Pull request by jackihann**
Updated the following:

- Labels to the authentication field name, placeholder text, and tooltip.
- Labels to some of the actions in the iAuditor connector. To improve the description of actions and action fields.

---
Please check the following conditions for your PR.

- [x] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [x] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Comment by sriyen-msft** [comment]
@jackihann Can you please change the target branch of this PR from `master` to `dev`
Please refer updated instructions in the [documentation](https://github.com/microsoft/PowerPlatformConnectors#contributing)

**Comment by dougelliott** [comment]
@jackihann It appears there are some conflicts with the branch. Would you be able to take a look at them and resolve? Thanks in advance!

**Comment by jackihann** [comment]
Sorry for missing that @dougelliott! Conflict resolved now 👍🏼

**Comment by jackihann** [comment]
Hey @sriyen-msft @dougelliott, just following up on the review for this PR :)

**Review by dougelliott — APPROVED** [review]

**Comment by jackihann** [comment]
Hey @sriyen-msft , are you able to review this PR? :)

**Review by sriyen-msft — APPROVED** [review]

**Pull request merged**
