### PR TITLE
update: HrFlow connector

### PR DESCRIPTION
**Pull request by nicolae-istratii**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by nicolae-istratii** [comment]
@microsoft-github-policy-service agree company="HrFlow.ai"

**Comment by vmanoharas** [comment]
Hello @nicolae-istratii, 

Below operations have been deleted, can you please confirm that no existing flows or users will be affected by this change?

##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/PostProfile Source: NewSwagger
##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/DocumentParsing Source: NewSwagger

**Comment by nicolae-istratii** [comment]
These operations have been replaced by their new equivalents. And more precisely, `PostProfile` has been replaced by `ProfileParsingFilePost` and `DocumentParsing` has been replaced by `TextParsingPost`.

Answering the question, some flows might be affected because the schemas of both have slightly changed.

**Comment by vmanoharas** [comment]
> These operations have been replaced by their new equivalents. And more precisely, `PostProfile` has been replaced by `ProfileParsingFilePost` and `DocumentParsing` has been replaced by `TextParsingPost`.
> 
> Answering the question, some flows might be affected because the schemas of both have slightly changed.

Hello @nicolae-istratii 

Thank you for your response. Could you please verify that the current flows will remain unaffected? Customers who rely on these flows may raise questions or encounter issues. If any alterations impact them, changes are not permitted.

**Comment by nicolae-istratii** [comment]
Hi @vmanoharas

Let me give a more detailed response to the previous question:

`PostProfile` (the endpoint has remained unchanged `/profile/parsing/file`)

its current parameters are (removed or replaced parameter names are followed by a `#`):
- x-user-email
- file
- source_key
- key
- reference
- created_at
- sync_parsing (#)
- sync_parsing_indexing (#)
- webhook_parsing_sending (#)
- labels (#)
- tags
- metadatas

its new parameters (added parameter names are followed by a `*`):
- x-user-email
- file
- source_key
- key
- reference
- created_at
- tags
- metadatas
- content_type (*)
- debugger (*)

As you can see, some parameters have been removed. The reason for this is that, those parameters continue to exist but are deprecated or unused. I'm referring to `sync_parsing`, `sync_parsing_indexing`, `webhook_parsing_sending` and `labels`.

`DocumentParsing` (its endpoint `/document/parsing` is available but deprecated, its newest version is `/text/parsing`)

its current parameters are (removed or replaced parameter names are followed by a `#`):
- x-user-email
- text (#)

its new parameters are (added parameter names are followed by a `*`):
- x-user-email
- texts (*)

As you can see, the parameters schema has slightly changed. The newest endpoint allows to send multiple texts to be parsed instead of a single one.

From the stats available in the ISV Studio, there are about 12 thousands monthly requests and 7 monthly active connections. Therefore, there are at most 7 active users per month. Some of these connections are ours since we use flows (I suppose these are counted in the given report).

I understand that breaking already existing flows is unwanted but the amount of **connections** is, in my opinion, not that high to completely avoid updating deprecated endpoints.

Proposed **solution**:
Return `PostProfile`, under its native name (if mandatory), without the unused parameters, and with its newest ones included.
Return `DocumentParsing` as it was. Basically, this means, coexisting with `TextParsingPost`.
What you think about it ?

**Comment by vmanoharas** [comment]
> Hi @vmanoharas
> 
> Let me give a more detailed response to the previous question:
> 
> `PostProfile` (the endpoint has remained unchanged `/profile/parsing/file`)
> 
> its current parameters are (removed or replaced parameter names are followed by a `#`):
> 
> * x-user-email
> * file
> * source_key
> * key
> * reference
> * created_at
> * sync_parsing (#)
> * sync_parsing_indexing (#)
> * webhook_parsing_sending (#)
> * labels (#)
> * tags
> * metadatas
> 
> its new parameters (added parameter names are followed by a `*`):
> 
> * x-user-email
> * file
> * source_key
> * key
> * reference
> * created_at
> * tags
> * metadatas
> * content_type (*)
> * debugger (*)
> 
> As you can see, some parameters have been removed. The reason for this is that, those parameters continue to exist but are deprecated or unused. I'm referring to `sync_parsing`, `sync_parsing_indexing`, `webhook_parsing_sending` and `labels`.
> 
> `DocumentParsing` (its endpoint `/document/parsing` is available but deprecated, its newest version is `/text/parsing`)
> 
> its current parameters are (removed or replaced parameter names are followed by a `#`):
> 
> * x-user-email
> * text (#)
> 
> its new parameters are (added parameter names are followed by a `*`):
> 
> * x-user-email
> * texts (*)
> 
> As you can see, the parameters schema has slightly changed. The newest endpoint allows to send multiple texts to be parsed instead of a single one.
> 
> From the stats available in the ISV Studio, there are about 12 thousands monthly requests and 7 monthly active connections. Therefore, there are at most 7 active users per month. Some of these connections are ours since we use flows (I suppose these are counted in the given report).
> 
> I understand that breaking already existing flows is unwanted but the amount of **connections** is, in my opinion, not that high to completely avoid updating deprecated endpoints.
> 
> Proposed **solution**: Return `PostProfile`, under its native name (if mandatory), without the unused parameters, and with its newest ones included. Return `DocumentParsing` as it was. Basically, this means, coexisting with `TextParsingPost`. What you think about it ?

Thank you very much @nicolae-istratii for being in detail.

**Review by vmanoharas — APPROVED** [review]
Hello @nicolae-istratii 
I hope you are doing well.
Congratulations, your pull request is approved and merged. Please [submit the files to ISV Studio](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) or [update your submission](https://learn.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#update-submission-prior-to-certification) using your latest commit ID, please allow us up to 1-2 weeks to review your submission, and our Engineers will notify you in the “Activity Control” area in ISV Studio. Please [make sure that the icon meets all the requirements](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-submission#design-an-icon-for-your-connector), that it’s size is 230x230, icon background is not white or transparent and it matches the iconBrandColor property in apiProperties.json file.
After making the submission in ISV Studio, please attach an intro.md file in the activity control section. This file is required and it's different from readme.md. You can [find an example of intro.md file on this page](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) at step 6.
Please [Create an environment in the Preview region](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#create-an-environment-in-the-preview-region). You will use this environment later to [test your connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#test-your-connector) after Microsoft is done with the functional verification for your connector.
We expect all tests to be completed within 1-2 weeks.
If your connector passes all tests, the deployment process begins, and it typically takes up to 3 to 4 weeks to deploy your connector to all of our regions.
Please let me know if you have any questions or run into any problems while creating or updating your submission.
Thank you very much for working with us.

**Pull request merged**
