### PR TITLE
HubSpot CRM: Updated some scopes that this connector uses (edit contacts, list and edit deals)

### PR DESCRIPTION
**Pull request by Cammeritz**
I have modified the scopes which this platform connector requests from HubSpot.

I noticed that some of the actions do not work due to missing scopes:
https://learn.microsoft.com/en-us/connectors/hubspotcrm/#list-deals
https://learn.microsoft.com/en-us/connectors/hubspotcrm/#update-a-contact
https://learn.microsoft.com/en-us/connectors/hubspotcrm/#update-a-deal

It could be possible that others are also not working anymore, maybe due to api changes from HubSpot.

@troystaylor since this is your connector, you might want to look more into it, at least these three should be fixed for now.

image

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by troystaylor** [comment]
Thanks, @Cammeritz for the update. Please know that it is my plan to fully update the HubSpot connectors now that I am receiving significant requests for a HubSpot Copilot plugin. These efforts are not exclusive, as plugin certification is still TBD, but I can give no estimate for when that would be completed.

**Comment by vmanoharas** [comment]
Hello @troystaylor, 

Thank you very much for your reply.  @Cammeritz can close this PR? please advise.

**Comment by Cammeritz** [comment]
> Hello @troystaylor, 
> 
> 
> 
> Thank you very much for your reply.  @Cammeritz can close this PR? please advise. 

In my opinion you should merge the change into the codebase. We need this feature and found out it's broken. I am just waiting for this fix to be applied so our MS Bookings <-> HubSpot integration is going to work.

**Comment by Cammeritz** [comment]
@troystaylor 
Can you please confirm for @vmanoharas that this change can be merged into the codebase?

**Comment by troystaylor** [comment]
Yes, this change can be merged.

**Review by vmanoharas — APPROVED** [review]
Hello @Cammeritz 
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by vmanoharas** [comment]
Hello Partner,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Pull request merged**
