### PR TITLE
Securities and Exchange Commission USA (Independent Publisher)

### PR DESCRIPTION
**Pull request by gulshankhurana**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, 

As mentioned in your other PR, this PR will be taken after your current deployment is completed. However, kindly remove proposal from the title of the PR.

**Comment by krautrocker** [comment]
Hi Gulshan,

Thanks for leading this, and glad to see an independent publisher taking the initiative.

I read the readme.md file. I assume that there will be more functionality in the connector. Those are indeed the four API endpoint links, but there are a few things that you need to be aware of and comfortable with while developing the connector. Further, the SEC still provides plenty of useful information but it's the scope is not as wide as the FCA. You may be disappointed, as the FCA has data on companies as well as individuals. SEC is only entities and their filings, statements, etc.

See my custom connector that already does this. Read [here](https://developments.substack.com/p/no-bull).

Dan

**Comment by vmanoharas** [comment]
Hello @gulshankhurana ,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
Thank you @krautrocker can you please confirm with me and @gulshankhurana, can we go ahead and proceed to certify this connector?

**Comment by rwilson504** [comment]
@gulshankhurana , Thank you for your contribution, I have been working at getting as many US Gov connectors out there as possible, I appreciate you adding to that list!

**Comment by krautrocker** [comment]
> Thank you @krautrocker can you please confirm with me and @gulshankhurana, can we go ahead and proceed to certify this connector?

Yes, of course, @vmanoharas. Apologies for the delay, I was out on vacation. @gulshankhurana, congrats on another connector! Perhaps one day we can link up and work together on a single product but let's get this out to users ASAP.

**Pull request closed without merging**
