### PR TITLE
FCA UK (Independent Publisher)

### PR DESCRIPTION
**Pull request by gulshankhurana**
Created Financial Conduct Authority (FCA) UK Connector folder and ReadME file underneath

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

Connector Action Definitions

Connector Operations Test

Common Search

Find Individual Details

Individual Disciplinary History

Product Other Name Details

Subfund Details

Firm Other Names

Firm Address

Firm Individuals

Firm Activities and Permissions

Firm Requirements

Firm Requirements Investment Types

Firm Regulators

Firm Passport

Firm Passport Permission

Firm Waiver

### CODE REVIEW

**Comment by gulshankhurana** [comment]
> @gulshankhurana please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by vmanoharas — APPROVED** [review]
Hello Partner,
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks. 
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by gulshankhurana** [comment]
[apiProperties.json](https://github.com/microsoft/PowerPlatformConnectors/files/14271745/apiProperties.json)
[apiDefinition.swagger.json](https://github.com/microsoft/PowerPlatformConnectors/files/14271746/apiDefinition.swagger.json)

**Review by gulshankhurana — COMMENTED** [review]
# FCA Connector

The Financial Conduct Authority (FCA) is a financial regulatory body in the United Kingdom. Their website allows people to search the Financial Services Register for firms and individuals and the activities firms have permissions for. The Financial Services Register is a public record of firms, individuals and other bodies that are authorised by the Prudential Regulation Authority (PRA) and/or FCA. The website can be used by anyone, looking to gather information.

# Publisher: Gulshan Khurana

## Prerequisites

You will need the following to proceed:
* A Microsoft Power Apps or Power Automate plan with custom connector feature
* An API key obtained [here](https://register.fca.org.uk/Developer/s/) and the email address used for registration

## Supported Operations

The connector supports the following operations:
* `Common Search`: Search the Financial Services Register for a firm or an individual by name or unique reference number
*  `Find Individuals Details`: Get information about the Individuals associated with its Individual Reference Number
*  `Individual Disciplinary History`: Get information about Disciplinary History on an Individual using its Individual Reference Number
*  `Subfund Details`: Get information about subfund of a product by using its Product Reference Number
*  `Product Other Name Details`: Get information about other names of a product by using its Product Reference Number
*  `Firm Other Names`: Get information about the other names used by the firms using its Firm Reference Number
*  `Firm Address`: Get information about a specific firm using its Firm Reference Number
*  `Firm Individuals`: Get information about the Individuals associated with a firm using its Firm Reference Number
*  `Firm Activities and Permissions`: Get information about the activities and permissions associated with a specific firm using its Firm Reference Number
*  `Firm Requirements`: Get information about the requirements associated with a specific firm using its Firm Reference Number
*  `Firm Requirements Investment Types`: Get information about the investment types associated with a specific firm requirement using its Firm Reference Number and Requirement Reference
*  `Firm Regulators`: Get information about a regulator on a firm using its Firm Reference Number
*  `Firm Passport`: Get information about a passport details by using its Firm Reference Number
*  `Firm Passport Permission`: Get information about a passport permission by using its Firm Reference Number and Country
*  `Firm Exclusions`: Get information about an Exclusion on a firm using its Firm Reference Number
*  `Firm Disciplinary History`: Get information about a Disciplinary History on a firm using its Firm Reference Number
*  `Firm Waiver`: Get information about a Waiver on a firm using its Firm Reference Number


## Obtaining Credentials

An API key and email address is required for this connector to work. You can sign up for free with an account on FCA's website [here](https://register.fca.org.uk/Developer/s/registernewuser)

## Known issues and limitations

There are no known issues with this connector. There are functions in the API not implemented in this connector and I will continue to work on these if I can resolve the functions/syntax.

## Deployment Instructions

Upload the connector and create a connection using the API key along with the registered email address from the prerequisites.

Go to the 'Definition' section of the connector (in edit mode), click on 'X-Auth-Email' policy under 'Policies' and ensure that, in 'Operations' field in the Policy Details that emerge on the screen, all operations listed there are ticked/checked.

**Pull request merged**
