### PR TITLE
OpenAI GPT-4 (Independent Publisher) v1.4 update

### PR DESCRIPTION
**Pull request by troystaylor**
Adding fine-tuning and moderation.

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [X] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [X] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by vmanoharas** [comment]
Hello @troystaylor, 

Can you please look into the Swagger validation check error and confirm that existing flows will be break due to the changes you made?

**Comment by troystaylor** [comment]
> Hello @troystaylor,
> 
> Can you please look into the Swagger validation check error and confirm that existing flows will be break due to the changes you made?

Existing flows will be broken now before the update, as the API has changed and only the newly added enumerated values are accepted by the API.

**Review by vmanoharas — DISMISSED** [review]
Hi @troystaylor 
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by vmanoharas** [comment]
Hello Partner,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
Hello @troystaylor, 

This connector is deployed to all the regions, can you please resolve conflicts, so that i can merge this PR?

**Comment by vmanoharas** [comment]
Hello @troystaylor, 

Can you please resolve the conflicts? I need to close this PR, as the connector deployed to all the regions.

**Comment by troystaylor** [comment]
That conflict will is an updated enum array with the currently available options. Previous values that have been used are no longer valid with the service and had to be removed.

**Comment by vmanoharas** [comment]
> That conflict will is an updated enum array with the currently available options. Previous values that have been used are no longer valid with the service and had to be removed.

Thank you for looking into it. Until the conflicts are resolved, I cannot merge this PR.  Please help in resolving this conflict.

**Comment by troystaylor** [comment]
I will not restore an enum value that is only going to give an error because the model is no longer available from the API. This should be an exception to the change validator.
@ShefaaliP

**Comment by vmanoharas** [comment]
Thank you very much @troystaylor for you quick response. Should this PR to be closed instead of merging?

image

image

**Comment by troystaylor** [comment]
I want this PR merged. Opening a new PR is going to result in the same validation error which will not block merging

**Comment by vmanoharas** [comment]
Hello @troystaylor. 

Thank you very much for your response, however, the conflict is not resolved yet.  Please resolve, else I cannot merge this PR. 

image

**Comment by troystaylor** [comment]
@vmanoharas You should now be able to resolve and merge the remaining version conflict

**Comment by vmanoharas** [comment]
Hello @troystaylor, 

The conflict is not yet resolved, please see the screen shot below of my view. 

image

**Comment by troystaylor** [comment]
@vmanoharas I am unable to resolve them as that button is disabled for me. You will need to merge it:
image

**Review by vmanoharas — APPROVED** [review]
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
@troystaylor, I have tried in many ways to resolve the conflicts, as this PR opened for many days, I am closing this PR.

**Pull request closed without merging**
