### PR TITLE
Kanbanize v1.5

### PR DESCRIPTION
**Pull request by kostadin-kanbanize**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`.

### CODE REVIEW

**Comment by kostadin-kanbanize** [comment]
We have applied some small fixes and changed titles and descriptions for the actions and triggers. Please review the changes.

**Comment by v-EgorKozhadei** [comment]
Hello @kostadin-kanbanize, 

Thank you very much for an update. Our Certification Engineers will review it within 1-2 weeks. 
Could you please check if your fork is up-to-date? There's a conflict between branches.

Please let us know if you have any questions. 

Thank you very much again for working with us.

**Comment by kostadin-kanbanize** [comment]
We have verified that the correct version of the files (apiDefinition.swagger.json and icon.png) is uploaded in Kanbanize-v1.5 branch. Please overwrite the conflicting files.

**Comment by v-EgorKozhadei** [comment]
Hi @kostadin-kanbanize,

Unfortunately, we cannot overwrite the conflicting files. Please update your fork and branch, it's many commits behind our dev branch and it causes conflicts.

**Comment by kostadin-kanbanize** [comment]
Hi, I have created new branch from dev and uploaded our new changes to it. This pull request will be closed and you can process the new one. 

Regards

**Pull request closed without merging**
