### PR TITLE
Google PaLM (Independent Publisher)

### PR DESCRIPTION
**Pull request by PriyaranjanKS**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

# API Endpoints

Below is a list of available API endpoints in Google PaLM which has been implemented

- **generateText**: Generates a response from the model given an input message.

- **generateMessage**: Generates a response from the model given an input MessagePrompt.

- **embedText**: Generates an embedding from the model given an input message.

- **get**: Gets information about a specific Model.

- **list**: Lists models available through the API.

- **countTextTokens**: Runs a model's tokenizer on a text and returns the token count.

- **countMessageTokens**: Runs a model's tokenizer on a string and returns the token count.

# Generate Text Sample 

### Without Parameters

Without Parameters

### With Parameters

With Parameters

### Output

Output

### CODE REVIEW

**Comment by PriyaranjanKS** [comment]
@vmanoharas  Requesting your review for submitting the proposed connector for Google PaLM which is not available currently in Power Automate ecosystem.

**Review by vmanoharas — COMMENTED** [review]
Hi @PriyaranjanKS, 
Could you please update your readme.md file and submit your PR.  

Please follow the below template and refer the IP documentation below. 
https://github.com/microsoft/PowerPlatformConnectors/tree/dev/templates/Independent%20Publisher 

https://learn.microsoft.com/en-us/connectors/custom-connectors/certification-submission-ip

**Review by vmanoharas — COMMENTED** [review]
Hello @PriyaranjanKS, 

This is approved, 
please format the readme.md file according to [the template](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/templates/certified-connectors/readme.md?plain=1). All of the required headings should be present.

Also please follow the other file formats as well mentioned in this [https://github.com/microsoft/PowerPlatformConnectors/tree/dev/templates/Independent%20Publisher](link)

**Comment by PriyaranjanKS** [comment]
@vmanoharas The readme has been updated and the swagger file has been uploaded for review and merge.

**Review by vmanoharas — DISMISSED** [review]
Hello @PriyaranjanKS 
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by vmanoharas** [comment]
Hello Partner,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Review by vmanoharas — APPROVED** [review]
Hello Partner,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Comment by PriyaranjanKS** [comment]
> Hello Partner, I hope you are doing well. Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program. Thank you very much for working with us.

Hello @vmanoharas  Thank You so much for your support and guidance in the submission process. I have 2 humble requests which needs your help.  

- Can you please assist in adding a Co-Publisher in the connection page and documentation. He had helped in the last rounds of the development. It will be of great help as I missed to add his name in the publisher details. His name is Vidya Sagar Alti. 

- While creating the connection, could see for other connectors that the publisher name is being shown as below :    
sample
However for the current published connector(as shown below) , the publisher names are not visible. Can we please add both the Publisher names (Priyaranjan KS and Vidya Sagar Alti) here ?
sample2

Thank You once again for your support ! 
Regards, 
Priyan

**Comment by vmanoharas** [comment]
> > Hello Partner, I hope you are doing well. Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program. Thank you very much for working with us.
> 
> Hello @vmanoharas Thank You so much for your support and guidance in the submission process. I have 2 humble requests which needs your help.
> 
> * Can you please assist in adding a Co-Publisher in the connection page and documentation. He had helped in the last rounds of the development. It will be of great help as I missed to add his name in the publisher details. His name is Vidya Sagar Alti.
> * While creating the connection, could see for other connectors that the publisher name is being shown as below :
>   sample
>   However for the current published connector(as shown below) , the publisher names are not visible. Can we please add both the Publisher names (Priyaranjan KS and Vidya Sagar Alti) here ?
>   sample2
> 
> Thank You once again for your support ! Regards, Priyan

Hello @PriyaranjanKS, 

Thank you very much for working with us!

However to answer your questions.  this PR is already merged after deployed to all the regions.  Please submit new PR with new changes.

**Pull request merged**
