### PR TITLE
Plumsail HelpDesk (Certified Publisher) - Added support of region selection when creating a new connection

### PR DESCRIPTION
**Pull request by antonkhrit**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

**Updates:** Added support for region selection when creating a new connection.

**Backward compatibility:** The update was tested with existing connectors and doesn't break old connections. Changes kick off only after connection recreation or editing.

### CODE REVIEW

**Comment by antonkhrit** [comment]
@microsoft-github-policy-service agree [company="Plumsail"]

**Comment by antonkhrit** [comment]
@microsoft-github-policy-service agree company="Plumsail"

**Comment by antonkhrit** [comment]
@vmanoharas, @souchoudhary, or any other reviewers. 

Do we need to do anything additional to pass API Properties Validator or we are just waiting for manual review? 

We tested backward compatibility. The changes don't affect existing connections, only connections that are newly created. So, no issues should occur with existing flows.

**Comment by vmanoharas** [comment]
Hello @antonkhrit
The pipeline was experiencing internal issues, we have resolved them. Could you please resubmit your PR/commit so that it can be triggered again and undergo validation? Thank you for your understanding. We apologize any inconvenience caused.

**Comment by antonkhrit** [comment]
Hello @vmanoharas,

I created [another pull request](https://github.com/microsoft/PowerPlatformConnectors/pull/2920) but the issue is the same. There is a validation error in the API Properties Validator.

**Pull request closed without merging**
