### PR TITLE
Badgr (Independent Publisher)

### PR DESCRIPTION
**Pull request by troystaylor**
brave_UcT957z6f4
brave_OatWzBB6cX

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [X] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [X] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [X] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [X] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by natalie-pienkowska** [comment]
Thanks, @troystaylor, for your Badgr Independent Publisher connector submission. Given that this week is Thanksgiving, we will resume validating PRs on Monday, 11/29.

**Comment by sriyen-msft** [comment]
[[certify-connector]]

**Comment by sriyen-msft** [comment]
@troystaylor Apologies for the delay in response, We have a high number of submissions and had to prioritize the connectors which were ready for production deployment.

I was trying to create a test account for this connector to set up OAuth app as the connection type of the connector is OAuth. It is mentioned that we need to email Badgr support team requesting for client id and secret which may not be possible for Microsoft. But I am following up with our management to see if there is any possibility. 
Can you please let us know if there is any way to get client credentials for a test account?

**Comment by Amjed-Ayoub** [comment]
Hi @troystaylor, we are looking forward to getting Badgr connector certified. 
Can you please let us know if there is any way to get client credentials for a test account? 
Thank you very much.

**Comment by troystaylor** [comment]
> Hi @troystaylor, we are looking forward to getting Badgr connector certified.
> Can you please let us know if there is any way to get client credentials for a test account?
> Thank you very much.

Badgr is free to use and you can signup at https://badgr.com/auth/signup

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor, I hope you are doing well. Apologies for the delay in the process. I want to notify you that we have created our account with Badgr for testing and we are moving forward with the certification process.
Please let me know if you have any questions.
Thank you for all your hard work with us.

**Comment by Amjed-Ayoub** [comment]
[[certify-connector]]

**Comment by Amjed-Ayoub** [comment]
Hi @troystaylor, I hope you are doing well. I want to follow up with you and let you know that your connector is in production deployment. this process will complete within 4 weeks.
Please let me know if you have any questions.
Thank you very much.

**Comment by Amjed-Ayoub** [comment]
Hi @troystaylor, I hope you are doing well.
Apologies for the delay in the deployment process. There was an issue with the deployment train that prevented us from completing your connector deployment. We are working to fix this issue; we will keep you posted.
Please let me know if you have any questions.
Thank you so much for your patience and understanding.

**Comment by sriyen-msft** [comment]
Hi @troystaylor, Apologies for the delay in response, We have been reaching out to Badgr team for Client credentials for the last 15 days, and we got a reply from them with client credentials, we are moving forward for production deployment and your connector will be published with documentation in next 3-4 weeks.

It seems your PR  has branch conflicts, kindly update your branch to resolve the conflicts as we need to approve and merge your PR as soon as your gets certified.

**Review by Amjed-Ayoub — APPROVED** [review]

**Pull request merged**
