### PR TITLE
Pug gamified engagement

### PR DESCRIPTION
**Pull request by smart-jp**
---
When submitting a connector, please check the following conditions for your PR to ensure a smooth certification process.

- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Review by sriyen-msft — CHANGES_REQUESTED** [review]
@smart-jp Can you please remove commas after each propertyValue, It is a syntax error.

Line number 724:

`"x-ms-connector-metadata" : [
    {
      "propertyName" : "Website",
      "propertyValue" : "https://www.puginteractive.com",
    },
    {
      "propertyName" : "Privacy policy",
      "propertyValue" : "https://www.puginteractive.com/privacy_policy",
    },
    {
      "propertyName" : "Categories",
      "propertyValue" : "Human Resources;Marketing",
    },
  ]`

**Comment by smart-jp** [comment]
thanks, commas removed

**Review by sriyen-msft — CHANGES_REQUESTED** [review]
@smart-jp Sorry for the late find - We do not need intro.md file in the open source repo, Can you please remove it from the PR to get it approved and merged.

**Comment by smart-jp** [comment]
removed intro.md file

**Review by sriyen-msft — APPROVED** [review]

**Pull request merged**
