### PR TITLE
Financial Conduct Authority (FCA) (Independent Publisher)

### PR DESCRIPTION
**Pull request by gulshankhurana**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

Connector Action Definitions

Connector Operations Test

Flow run - Firm

Flow run - rest of flow

Common Search

Find Individual Details

Individual Disciplinary History

Product Other Name Details

Subfund Details

Firm Address

Firm Other Names

Firm Individuals

Firm Activities and Permissions

Firm Passport

Firm Passport Permission

Firm Regulators

Firm Requirements

Firm Requirements Investment Types

Firm Waiver

Firm Disciplinary History

Firm Exclusions

### CODE REVIEW

**Comment by gulshankhurana** [comment]
@vmanoharas, submitted it again as per your instructions.

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, 

Thank you very much for creating new PR!

However, please see the screenshot below, there are two folders created with the same name.  Could you please correct this and make it one folder?

image

**Comment by gulshankhurana** [comment]
Hi @vmanoharas 

Please check and confirm if all ok now. 

Thanks.

Gulshan

**Review by vmanoharas — APPROVED** [review]
Hello @gulshankhurana 
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by vmanoharas** [comment]
[[certify-connector]]

**Comment by gulshankhurana** [comment]
Dear @vmanoharas 

Wondering if there's a date by when it is likely to be implemented/available.

Kind regards
Gulshan

**Comment by vmanoharas** [comment]
Hello @gulshankhurana, 

Your connector picked in last week's deployment, now it is in westus2 region.  Please allow us to deploy to other regions in 1 to 2 weeks.

**Comment by gulshankhurana** [comment]
> Hello @gulshankhurana,
> 
> Your connector picked in last week's deployment, now it is in westus2 region. Please allow us to deploy to other regions in 1 to 2 weeks.

Thanks @vmanoharas. Is there any update available regading a date by when it is likely to be implemented/available and if/how/when will I get a notification regarding this?

**Comment by vmanoharas** [comment]
> > Hello @gulshankhurana,
> > Your connector picked in last week's deployment, now it is in westus2 region. Please allow us to deploy to other regions in 1 to 2 weeks.
> 
> Thanks @vmanoharas. Is there any update available regading a date by when it is likely to be implemented/available and if/how/when will I get a notification regarding this?

Hello @gulshankhurana, 

This connector will be deployed to all the regions by coming Friday.

**Comment by vmanoharas** [comment]
Hello Partner,
I hope you are doing well.
Congratulations, the deployment of your connector and documentation page was already completed, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program.
Thank you very much for working with us.

**Comment by gulshankhurana** [comment]
Hi @vmanoharas 

I noticed that 
1. this connector is listed to be available for Logic Apps only. Is there any reason why it is not listed to be also available for Power Automate and Power Apps?
2. The title says 'FCA (Independent Publisher) (Preview)' whilst it should be 'Financial Conduct Authority (FCA) (Independent Publisher) (Preview)'

Please could the Title and Description be updated to reflect the points raised above.

Thanks.

Gulshan

**Comment by vmanoharas** [comment]
> Hi @vmanoharas
> 
> I noticed that
> 
> 1. this connector is listed to be available for Logic Apps only. Is there any reason why it is not listed to be also available for Power Automate and Power Apps?
> 2. The title says 'FCA (Independent Publisher) (Preview)' whilst it should be 'Financial Conduct Authority (FCA) (Independent Publisher) (Preview)'
> 
> Please could the Title and Description be updated to reflect the points raised above.
> 
> Thanks.
> 
> Gulshan

Hello @gulshankhurana 
Thank you very much for reaching out, please find my _answers_ below. 

1. this connector is listed to be available for Logic Apps only. Is there any reason why it is not listed to be also available for Power Automate and Power Apps?
_There is no specific environment deployment chosen to Independent Publishers, it will be deployed to all three, Logic Apps, Power Apps and Power Automate._ 
 
2. The title says 'FCA (Independent Publisher) (Preview)' whilst it should be 'Financial Conduct Authority (FCA) (Independent Publisher) (Preview)'
_This is depends on the title you specified in the apiDefinition.Swagger.json file.  If you would like to change the name of the connector, please update and re-submit your connector._

**Pull request merged**
