### PR TITLE
Jira Search independent connector

### PR DESCRIPTION
**Pull request by paulculmsee**
---
When submitting a connector, please check the following conditions for your PR.

- [ x] I attest that the connector works and I verified by deploying and testing all the operations.
- [x ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ x] I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`.

### CODE REVIEW

**Comment by mamurshe** [comment]
[[certify-connector]]

**Comment by mamurshe** [comment]
[[certify-connector]]

**Comment by mamurshe** [comment]
[[certify-connector]]

**Comment by mamurshe** [comment]
[[certify-connector]]

**Comment by mamurshe** [comment]
[[certify-connector]]

**Comment by mamurshe** [comment]
[[certify-connector]]

**Comment by sriyen-msft** [comment]
[[certify-connector]]

**Review by mamurshe — APPROVED** [review]

**Pull request merged**
