### PR TITLE
[timeghost] bugfix $filter-date-range

### PR DESCRIPTION
**Pull request by MarcHochleutner-Koellisch**
---
Please check the following conditions for your PR.

- [x] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [x] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Comment by sriyen-msft** [comment]
@MarcHochleutner-Koellisch Can you please change the target branch of this PR from `master` to `dev`. Please refer [documentation](https://github.com/microsoft/PowerPlatformConnectors#contributing)

**Comment by sriyen-msft** [comment]
@MarcHochleutner-Koellisch Please approve that the change in required parameter will not affect existing users of your connector.

**Comment by MarcHochleutner-Koellisch** [comment]
@dougelliott I just created the PR to dev. 
@sriyen-msft Yes, I confirm that. Users are forced to make this setting to be able to work with the action. No users are therefore affected.

**Comment by dougelliott** [comment]
@MarcHochleutner-Koellisch Thanks for creating the other PR and confirmation on the changes. I'll close out this PR is favor of #424

**Pull request closed without merging**
