### PR TITLE
CardPlatform moving to certified connectors

### PR DESCRIPTION
**Pull request by st0014**
---
Please check the following conditions for your PR.

- [x] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [x] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Comment by sriyen-msft** [comment]
@st0014 Can you please let us why you have added another connector's file in your PR. Also can you please make sure that your local repo is updated with the remote repo.

**Comment by st0014** [comment]
> @st0014 Can you please let us why you have added another connector's file in your PR. Also can you please make sure that your local repo is updated with the remote repo.

I originally placed the files in the wrong directory - I by mistake place them in the custom-connectors directory rather than certified-connectors, so I have moved them.

Also I'm not an expert with github - how do I update my local repo with the remote repo?

Thanks

**Comment by st0014** [comment]
Please can I get an update on this?

I really would like to move this forward to the next stage of submitting it to the ISV studio

Thanks

**Comment by st0014** [comment]
Closing - will open a new one with latest code

**Pull request closed without merging**
