### PR TITLE
Create Wikimedia connector

### PR DESCRIPTION
**Pull request by Yusadem131**
Proposal
Student
Independent Publisher
Daily counts
Get a pageview count timeseries of en.wikipedia's article Albert Einstein for the month of October 2015:

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by Amjed-Ayoub** [comment]
Hello @Yusadem131,
Thank you so much for your new proposal submission. We are looking forward to seeing your connector artifacts soon.
Please let us know if you have any questions.
Thank you so much again for working with us.

**Comment by Yusadem131** [comment]
I tried to download the artifacts using paconn but I am facing some errors
(base) PS C:\Users\USER> paconn download
Please select an environment:
 [1] Yusuf Abdulakeem's Environment
 [2] 1xls68 (default)
Please enter a choice [Default choice(1)]: 1
Environment selected: Yusuf Abdulakeem's Environment
Please select a connector:

Please enter a choice [Default choice(1)]: 1
Valid values are []
Please select a connector:

Please enter a choice [Default choice(1)]: 2
Valid values are []
Please select a connector:

Please enter a choice [Default choice(1)]: wikimedia connector
Valid values are []
Please select a connector:

Please enter a choice [Default choice(1)]: []
Valid values are []
Please select a connector:

Please enter a choice [Default choice(1)]: [wikimedia]
Valid values are []
Please select a connector:

**Comment by Yusadem131** [comment]
How do I also paste the screenshot of PR testing success here. I have been able to run the connector on powerplaltform successfully.

**Comment by Yusadem131** [comment]
@Amjed-Ayoub kindly review this for validation

**Comment by troystaylor** [comment]
> I tried to download the artifacts using paconn but I am facing some errors (base) PS C:\Users\USER> paconn download Please select an environment: [1] Yusuf Abdulakeem's Environment [2] 1xls68 (default) Please enter a choice [Default choice(1)]: 1 Environment selected: Yusuf Abdulakeem's Environment Please select a connector:
> 
> Please enter a choice [Default choice(1)]: 1 Valid values are [] Please select a connector:
> 
> Please enter a choice [Default choice(1)]: 2 Valid values are [] Please select a connector:
> 
> Please enter a choice [Default choice(1)]: wikimedia connector Valid values are [] Please select a connector:
> 
> Please enter a choice [Default choice(1)]: [] Valid values are [] Please select a connector:
> 
> Please enter a choice [Default choice(1)]: [wikimedia] Valid values are [] Please select a connector:

Is your connector in the default (2) environment?

**Comment by Yusadem131** [comment]
@troystaylor. Yes, it is.

**Comment by troystaylor** [comment]
> @troystaylor. Yes, it is.

After you type paconn download, the first option you have is to pick the environment. The default is 1, so you need to enter 2 to pick connectors from that environment.

**Comment by Yusadem131** [comment]
I have downloaded my connector artifact.

How do I upload it here

**Comment by Yusadem131** [comment]
file:///C:/Users/USER/Pictures/wikimedia%20test%203png.png

**Comment by troystaylor** [comment]
> I have downloaded my connector artifact.
> 
> How do I upload it here

Have you run paconn validate —api-def apiDefinition.swagger.json ?

**Comment by Yusadem131** [comment]
https://github.com/Yusadem131/Wikimedia-testing-images.git

@Amjed-Ayoub 
The artifact and the images are here for testing.
You may proceed to the certification phase. Thanks

**Comment by Amjed-Ayoub** [comment]
Hi @Yusadem131 thank you so much for sharing this with us.
May I ask you please to add your artifacts to this pull request. 
Thank you so much.

**Comment by Yusadem131** [comment]
wikimedia testing
wikimedia test 3png
wikimedia testing2

**Comment by Yusadem131** [comment]
{
  "swagger": "2.0",
  "info": {
    "title": "Default title",
    "description": "Daily counts",
    "version": "1.0"
  },
  "host": "wikitech.wikimedia.org",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "consumes": [],
  "produces": [],
  "paths": {
    "/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/Albert_Einstein/daily/2015100100/2015103100": {},
    "/w/api.php": {
      "get": {
        "responses": {
          "default": {
            "description": "default",
            "schema": {}
          }
        },
        "summary": "wikimedia",
        "description": "Daily counts",
        "operationId": "Getwikimedia",
        "x-ms-visibility": "internal",
        "parameters": [
          {
            "name": "action",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Wikimedia",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "abusefiltercheckmatch",
            "x-ms-visibility": "internal",
            "format": "html"
          },
          {
            "name": "prop",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "iiprop",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "iimetadataversion",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ]
      }
    },
    "/wiki/Special:MyLanguage/API:Main_page": {
      "get": {
        "responses": {
          "default": {
            "description": "default",
            "schema": {}
          }
        },
        "parameters": [],
        "summary": "to abuse filter check match",
        "operationId": "GET",
        "x-ms-visibility": "internal",
        "description": "abusefiltercheckmatch"
      }
    }
  },
  "definitions": {},
  "parameters": {},
  "responses": {},
  "securityDefinitions": {},
  "security": [],
  "tags": []
}


Hi @Amjed-Ayoub. Above is my artifact.

Kindly move to certification level. Thanks

**Comment by Amjed-Ayoub** [comment]
Hello @Yusadem131,

Please add all your artifacts in your connector folder.

1. apiDefinition.swagger.json
2. apiProperties.json
3. readme.md

**Comment by Yusadem131** [comment]
I will need your assistance through a call. The paconn isn't working on my machine. Thanks

**Comment by Amjed-Ayoub** [comment]
Hi @Yusadem131,

Yes I will send you a meeting invite via email. can you please make sure to have your artifacts ready for submission. Please have the below files ready.

1. apiDefinition.swagger.json
2. apiProperties.json
3. readme.md

Thank you so much.

**Comment by Amjed-Ayoub** [comment]
@Yusadem131 please let me know when you have your connector files ready :-)

**Comment by Yusadem131** [comment]
Hi Amjed,
Can we have the meeting on Sunday by 7:00am Gmt+1. Thanks.

Best Regards,
Abdulakeem Yusuf A.

**Comment by Amjed-Ayoub** [comment]
Hello @Yusadem131,
I hope you are doing well.
I am following up with you to see how things are going with preparing your connector.
Please let us know if you have any questions.
Thank you.

**Comment by Yusadem131** [comment]
Hello @Amjed-Ayoub,
I am glad to hear from you. Please, when can I have a meeting with you? Thanks

**Comment by Amjed-Ayoub** [comment]
Hello @Yusadem131,

Do have the below files ready and validated?

1. apiDefinition.swagger.json
2. apiProperties.json
3. readme.md

You can [validate ](https://learn.microsoft.com/en-us/connectors/custom-connectors/paconn-cli#validate-a-swagger-json)using our [paconn tool](https://learn.microsoft.com/en-us/connectors/custom-connectors/paconn-cli).

I look forward to hearing from you.

Thank you so much again.

**Comment by Yusadem131** [comment]
Hello @Amjed-Ayoub,
I have gotten it ready in my laptop but it was just stolen December 3rd when I went for a tech event and I haven't been able to get another laptop.

**Comment by Amjed-Ayoub** [comment]
Hello @Yusadem131,

I am really sorry to hear that. please recreate the connector files and validate them. 

I look forward to hearing from you.

Thank you so much.

**Comment by Amjed-Ayoub** [comment]
Hello @Yusadem131 ,

I hope you are doing well.

We would like to know the status of your connector. It has been in our repo since October 2022.
Please let us know how you would like to proceed.

Please do not hesitate to reach out if you have any questions as we are always happy to help.

Thank you very much.

**Comment by Yusadem131** [comment]
Thanks @Amjed-Ayoub. Though, I have created the artifact. I haven't been able to get a laptop.

**Comment by vmanoharas** [comment]
Hello @Yusadem131 
I hope you are doing well.

Your connector has been in our repo since October 2022, hence we are closing this PR.  Please create a new PR whenever your artifacts are ready. 

Thank you very much for you patience and understadning.

**Comment by Yusadem131** [comment]
Hi @Amjed-Ayoub . I have submitted my artifact.

**Pull request closed without merging**
