### PR TITLE
Added Connector for JitBit HelpDesk

### PR DESCRIPTION
**Pull request by Pieter-Veenstra**
---
Please check the following conditions for your PR.

- [ ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

### CODE REVIEW

**Review by sriyen-msft — CHANGES_REQUESTED** [review]
@Pieter-Veenstra Please update the artifacts as per the given feedback in the certification portal

**Comment by sriyen-msft** [comment]
@Pieter-Veenstra I can see 9 files are uploaded where we expected only 3 files (apiDefinition.json, apiProperties.json and readme.md) for open souring your connector. Can you please delete remaining all the files and duplicate files.

**Comment by dougelliott** [comment]
@Pieter-Veenstra Checking in on things. Were there any questions about @sriyen-msft's feedback above?

**Comment by dougelliott** [comment]
Closing for now as per email

**Pull request closed without merging**
