### PR TITLE
DHL shipment tracking (Independent Publisher)

### PR DESCRIPTION
**Pull request by last72**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
image
- [x] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
image
- [x] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by v-EgorKozhadei** [comment]
Hi @last72!

Thank you for your submission!
We can't start the review process because the PR is in Draft status. Are you going to update it?
If yes, we'll need to make a few updates because Swagger and Change Validation check fails, you can see the details below the messages. 

Please let me know if you need any help!

**Comment by last72** [comment]
@v-EgorKozhadei The swagger file is not finished yet. I'll make some more changes and change the status of PR when ready

**Review by v-EgorKozhadei — COMMENTED** [review]
Hi @last72! Thank you for your submission! Please check comments after the review, we need to fix a few minor things before we can proceed to the next step.

**Comment by sriyen-msft** [comment]
[[certify-connector]]

**Comment by v-EgorKozhadei** [comment]
Hello @last72, 

I hope you are doing well. 

Your connector is in production deployment and queued up for the next deployment schedule. This process typically takes 3-4 weeks. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps. 

Please let us know if you have any questions. 

Thank you very much for working with us.

**Review by sriyen-msft — APPROVED** [review]

**Comment by sriyen-msft** [comment]
@last72 Congratulations! The deployment of your connector and documentation page is now complete, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program, Thanks.

**Comment by JakubZizka** [comment]
Dear all,
I am reaching out to you on behalf of our organization the DHL Group. We noticed this connector some time ago and we actively attempted to contact the independent publisher directly. However, neither website nor other contacts' work. We even tried Microsoft Premium support, and we got nowhere.

We respect that our API is public therefore available. However, we do not like it uses our name, and the documentation even uses our logo. Therefore, we would like to request decommissioning of the connector. Even more since the independent publishers' details and contacts are invalid. It does not represent our organization well at all.

You can respond here or via jakub.zizka @ dhl.com

Thank you

**Comment by last72** [comment]
@JakubZizka, sorry to hear that you were unable to contact. I am the one who created this connector and you can contact me via woong.choi@rapidcircle.com
I am unsure why the DHL logo was displayed at any point as independent publisher connector does not have specific logo but a generic logo. Reach out to me regarding decommissioning process. 
Regards, Woong

**Pull request merged**
