### PR TITLE
Proposal - Xero OAuth 2.0 (Independent Publisher)

### PR DESCRIPTION
**Pull request by philstubbington**
---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by troystaylor** [comment]
Hi Phil,
I'm one of the project coordinators for this project and I have worked on Xero connectors before. Your proposal lists the OAuth authentication and the Invoices endpoint - can you tell me more about your plans to develop the rest of the endpoints and/or if you are looking for assistance?

Best,
Troy

**Comment by philstubbington** [comment]
Hi Troy,

I’m working on adding all the rest of the end points, and certainly happy to collaborate.  No particular time frame in mind, although with more technically minded (I used to be very technical about 30 years ago 😉) people involved I’m sure it could be sped up!

Thanks.

Regards,
Phil Stubbington
Director
Henley Ridge Management Consulting Limited

d: +442045229074<applewebdata://03ACC645-A773-4731-8FCF-0F923549998B/+442045229074>


From: Troy Taylor ***@***.***>
Date: Wednesday, 6 July 2022 at 16:18
To: microsoft/PowerPlatformConnectors ***@***.***>
Cc: Phil Stubbington ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/PowerPlatformConnectors] Proposal - Xero (Independent Publisher) (PR #1785)

Hi Phil,
I'm one of the project coordinators for this project and I have worked on Xero connectors before. Your proposal lists the OAuth authentication and the Invoices endpoint - can you tell me more about your plans to develop the rest of the endpoints and/or if you are looking for assistance?

Best,
Troy

**Comment by v-EgorKozhadei** [comment]
Hi @philstubbington!

Thank you for your submission!

Your PR is missing apiDefinition.swagger.json and apiProperties.json files.
Templates for these files can be found [here](https://github.com/microsoft/PowerPlatformConnectors/tree/dev/templates/Independent%20Publisher).

Please let me know if you have any questions!

**Comment by natalie-pienkowska** [comment]
I agree @troystaylor ! We'll wait until you've removed the "Proposal" in the title and that will signify that you're completely ready to have your connector published :)

@v-EgorKozhadei for FYI

**Comment by philstubbington** [comment]
Hi everyone,

That's fine.  As I mentioned in the readme I'm treating this as an iterative process - there are quite a lot of API sets - so will submit for review once (fingers crossed) one of the API sets is complete.

On a related note, the format required for the API swagger file is quite different to what you see in the custom connector swagger.  Is there a way to automatically convert from one to the other?

Thanks
Phil

**Comment by troystaylor** [comment]
> Hi everyone,
> 
> That's fine. As I mentioned in the readme I'm treating this as an iterative process - there are quite a lot of API sets - so will submit for review once (fingers crossed) one of the API sets is complete.
> 
> On a related note, the format required for the API swagger file is quite different to what you see in the custom connector swagger. Is there a way to automatically convert from one to the other?
> 
> Thanks Phil

Xero provides their APIs in the OpenAPI 3.0 format (https://github.com/XeroAPI/Xero-OpenAPI), but the Power Platform currently uses Swagger 2.0. So, you have three choices:

1. Manually create all actions in the Custom Connector editor. This will be time consuming and require you to enter titles/summaries and descriptions but is the way to build a connector when the service doesn't provide a definition file.
2. Use a service like APIMatic's API Transformer (https://www.apimatic.io/transformer/) to convert the file. (Hint: they do have a free trial).
3. Wait for the Power Platform to bring a file converter to the Custom Connector editor and import the file(s) as a new connector. This is currently being rolled-out to the global regions and is expected to be in all regions by the end of the month. From my testing, this is not available in the United States region yet.

**Comment by Amjed-Ayoub** [comment]
Hello @philstubbington,
I hope you are doing well.
I am following up with you to see how things are going with preparing your connector.
Please let us know if you have any questions.
Thank you.

**Comment by Amjed-Ayoub** [comment]
Hello @philstubbington ,

I hope you are doing well.

We would like to know the status of your connector. It has been in our repo since July 2022.
Please let us know how you would like to proceed.

Please do not hesitate to reach out if you have any questions as we are always happy to help.

Thank you very much.

**Comment by vmanoharas** [comment]
Hello @philstubbington, 

I hope you are doing well.

Your connector has been in our repo since July 2022. I am closing this PR.  Please resubmit as new PR when you are ready with your connector. 

Thank you very much.

**Pull request closed without merging**
