### PR TITLE
Adding SMSLink Connector to Microsoft Power Automate, Power Apps, and Azure Logic Apps connectors

### PR DESCRIPTION
**Pull request by smslink**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### CODE REVIEW

**Comment by dougelliott** [comment]
@smslink Would you be able to fork off of master and recreate the PR for the commit to go into master as well? Thanks in advance.

**Comment by smslink** [comment]
> @smslink Would you be able to fork off of master and recreate the PR for the commit to go into master as well? Thanks in advance.

I have commited to master as well a few seconds ago. Thanks!

**Comment by smslink** [comment]
> > @smslink Would you be able to fork off of master and recreate the PR for the commit to go into master as well? Thanks in advance.
> 
> I have commited to master as well a few seconds ago. Thanks!

**Comment by smslink** [comment]
> @smslink Would you be able to fork off of master and recreate the PR for the commit to go into master as well? Thanks in advance.

@dougelliott I have commited to master as well a few seconds ago. Thanks!

**Comment by dougelliott** [comment]
@smslink Perfect, thanks! We'll go ahead and close this one out and look at #316

**Pull request closed without merging**
