### PR TITLE
OpenAI (Independent Publisher) v1.1 Add New Completion and Edit actions

### PR DESCRIPTION
**Pull request by troystaylor**
Please certify after @PowerRobin has given approval.

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [X] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor,
Thank you very much and congratulations on your new submission. Our Certification Engineers will review it within 1-2 weeks.
Please let us know if you have any questions.
Thank you very much again for working with us.

**Comment by PowerRobin** [comment]
I'm talking with Troy on twitter.

The additions are really great!

We also discovered that the old "Completion" endpoint that is currently used is already deprecated, so we are looking for a solution going forward. I'm completely fine with everything Troy proposes. He has got far more experience in APIs and especially Custom Connectors than me (and everyone else on the planet 😅), so I'm happy for any guidance.

**Comment by troystaylor** [comment]
@Amjed-Ayoub Schema and script have been updated. Please remove the hold and onward with the certification.

**Comment by Amjed-Ayoub** [comment]
[[certify-connector]]

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor,
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks. 
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by troystaylor** [comment]
@Amjed-Ayoub Please note that I have just updated the connector with the new (as of today) chat completion endpoint that uses GPT-3.5. Please let me know if it cannot be added to the train at this point. 

CC: @PowerRobin @jopanchal

**Comment by troystaylor** [comment]
image

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor, thank you again for submitting an update. Yes, we will include it.

**Comment by Amjed-Ayoub** [comment]
[[certify-connector]]

**Comment by Amjed-Ayoub** [comment]
[[certify-connector]]

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor,
I hope you are doing well.
Your connector is in production deployment and queued up for the next deployment schedule. This process typically takes 3-4 weeks. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps.
Please let us know if you have any questions.
Thank you very much for working with us.

**Comment by troystaylor** [comment]
@Amjed-Ayoub @jopanchal - Can @PowerRobin and I get an update on the deployment of this update?

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor,

Thank you for following up with us. We paused the deployment for this version as we mentioned in the email thread. we are waiting for you to confirm the root cause for these 400s errors :-)

I look forward to hearing from you.

Thank you so much.

**Comment by troystaylor** [comment]
@Amjed-Ayoub, please continue with the deployment. Robin and I both believe these are due to user error with no requirements that we can set on the parameters.

**Comment by Amjed-Ayoub** [comment]
Hello @troystaylor, it looks like this is a regression, meaning that requests which were coming back with successful 2xx responsecode, after the new version was deployed, they started to come back as failure 4xx responsecode. 
I will try to investigate more on our side and provide some data for you in the email so you can investigate as well.

**Comment by troystaylor** [comment]
There are two things that I've added that might be affecting this. The only thing I added directly to the action is the deprecated flag: 
image
Then I added the script to handle which only changes the CompletionPost action. I'm going to take out this bit to see if this is causing errors with the other actions (but it doesn't in my environment):
image

**Comment by PowerRobin** [comment]
Really can't see how @troystaylor could throw 4xx errors.

Is there any way to try the deployed version @Amjed-Ayoub (create environment in specific region)

**Comment by davidyack** [comment]
@troystaylor For me if I try to use the Script.csx on this pull  it is missing a closing } - it also complains after you fix that about not all paths return a value from ExecuteAsync 

image

**Comment by davidyack** [comment]
I believe you are looking for more like the following snippet that can either forward untouched or you could return an invalid operation like https://learn.microsoft.com/en-us/connectors/custom-connectors/write-code#forwarding-script 

```
   public override async Task<HttpResponseMessage> ExecuteAsync()
    {
    
        if (this.Context.OperationId == "CompletionPost") 
        {
            return await this.ConvertAndTransformOperation().ConfigureAwait(false);
        }

        HttpResponseMessage response = await this.Context.SendAsync(this.Context.Request, this.CancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        return response;
    }
```

**Comment by davidyack** [comment]
@Amjed-Ayoub  what else is needed to move this forward?

**Comment by Amjed-Ayoub** [comment]
> @Amjed-Ayoub what else is needed to move this forward?

@davidyack , @troystaylor and @PowerRobin 
May I ask you please to confirm if you found a root cause for this regression? can you please share some information?

can you please clarify if you want to deploy this version to preview region only for testing?

I look forward to hearing from you.

Thank you so much again.

**Comment by troystaylor** [comment]
I do not know how to fix the regression, nor do I have enough information to understand what is causing it. At this point, I am almost going to suggest that the new version with the action I've built be submitted as a separate connector.
CC: @jopanchal @PowerRobin

**Comment by PowerRobin** [comment]
I agree @troystaylor
I suggest, that I create a small update with the bare minimum to add the new completion action plus chat gpt and we'll try your stuff as an extra connector.

Really want to get that going. Many people already asked for the new endpoints...

**Pull request closed without merging**
