### PR TITLE
Chat update and delete chat thread properties

### PR DESCRIPTION
**Pull request by anmolbohra97**
---

Added the below operations:
1. Update Chat Thread Properties
2. Delete Chat Thread

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

### CODE REVIEW

**Review by kagbakpem — APPROVED** [review]

**Review by vmanoharas — COMMENTED** [review]
Hello @anmolbohra97, 

Could you please resolve below validation errors? Additionally, can you please confirm that no existing flows or users will be affected by this change?


##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/ListAllModels Source: NewSwagger
##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/CreateModel Source: NewSwagger
##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/UploadImageSamples Source: NewSwagger
##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/QueueTrainingJob Source: NewSwagger
##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/ListInferenceJobs Source: NewSwagger
##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/GenerateImage Source: NewSwagger
##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/GetSingleInferenceJob Source: NewSwagger
##[error]The operation has been deleted. This change breaks existing flows. ValuePath: operation/DeleteInference Source: NewSwagger

**Comment by v-vprasannak** [comment]
@vmanoharas Looks like validations are passed

**Review by vmanoharas — COMMENTED** [review]
Hello @anmolbohra97, 

Your commit has conflict with other repositories, please check validation errors, close this PR and open a new PR please.

**Review by vmanoharas — COMMENTED** [review]
Hello @anmolbohra97,

Can you please look into the swagger validation errors? the errors are not belongs to your connector, they are referring to other connectors in the repository.  The commit is not done properly it seems, please check. If it doesn't work this time, let me approve the PR.

**Comment by anmolbohra97** [comment]
Hello @vmanoharas , I have created a new PR. Here's a link to that: https://github.com/microsoft/PowerPlatformConnectors/pull/3311

**Comment by vmanoharas** [comment]
Hello @anmolbohra97, 

As you created a new PR and the same is approved, so I am closing this PR.

**Pull request closed without merging**
